# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off
from __future__ import annotations

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template actions.py.jinja --
from typing import TypeVar
import warnings

from . import types, errors, bases
from ._compat import model_parse

if TYPE_CHECKING:
    from .client import Client
    from .bases import _PrismaModel


_PrismaModelT = TypeVar('_PrismaModelT', bound='_PrismaModel')


class ScrapeJobActions(Generic[_PrismaModelT]):
    __slots__ = (
        '_client',
        '_model',
    )

    def __init__(self, client: 'Client', model: Type[_PrismaModelT]) -> None:
        self._client = client
        self._model = model

    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
    ) -> List[_PrismaModelT]:
        """Execute a raw SQL query

        Parameters
        ----------
        query
            The raw SQL query string to be executed
        *args
            Parameters to be passed to the SQL query, these MUST be used over
            string formatting to avoid an SQL injection vulnerability

        Returns
        -------
        List[prisma.models.ScrapeJob]
            The records returned by the SQL query

        Raises
        ------
        prisma_errors.RawQueryError
            This could be due to invalid syntax, mismatched number of parameters or any other error
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        users = await ScrapeJob.prisma().query_raw(
            'SELECT * FROM ScrapeJob WHERE id = $1',
            'bbadfchfja',
        )
        ```
        """
        return await self._client.query_raw(query, *args, model=self._model)

    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
    ) -> Optional[_PrismaModelT]:
        """Execute a raw SQL query, returning the first result

        Parameters
        ----------
        query
            The raw SQL query string to be executed
        *args
            Parameters to be passed to the SQL query, these MUST be used over
            string formatting to avoid an SQL injection vulnerability

        Returns
        -------
        prisma.models.ScrapeJob
            The first record returned by the SQL query
        None
            The raw SQL query did not return any records

        Raises
        ------
        prisma_errors.RawQueryError
            This could be due to invalid syntax, mismatched number of parameters or any other error
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        user = await ScrapeJob.prisma().query_first(
            'SELECT * FROM ScrapeJob WHERE status = $1',
            'dhheabfhf',
        )
        ```
        """
        return await self._client.query_first(query, *args, model=self._model)

    async def create(
        self,
        data: types.ScrapeJobCreateInput,
        include: Optional[types.ScrapeJobInclude] = None
    ) -> _PrismaModelT:
        """Create a new ScrapeJob record.

        Parameters
        ----------
        data
            ScrapeJob record data
        include
            Specifies which relations should be loaded on the returned ScrapeJob model

        Returns
        -------
        prisma.models.ScrapeJob
            The created ScrapeJob record

        Raises
        ------
        prisma.errors.MissingRequiredValueError
            Value is required but was not found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # create a ScrapeJob record from just the required fields
        scrapejob = await ScrapeJob.prisma().create(
            data={
                # data to create a ScrapeJob record
                'linkedinUrls': Json({'ggciceaie': True}),
                'maxPosts': 1147902781,
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='create',
            model=self._model,
            arguments={
                'data': data,
                'include': include,
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def create_many(
        self,
        data: List[types.ScrapeJobCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> int:
        """Create multiple ScrapeJob records at once.

        This function is *not* available when using SQLite.

        Parameters
        ----------
        data
            List of ScrapeJob record data
        skip_duplicates
            Boolean flag for ignoring unique constraint errors

        Returns
        -------
        int
            The total number of records created

        Raises
        ------
        prisma.errors.UnsupportedDatabaseError
            Attempting to query when using SQLite
        prisma.errors.UniqueViolationError
            A unique constraint check has failed, these can be ignored with the `skip_duplicates` argument
        prisma.errors.MissingRequiredValueError
            Value is required but was not found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        total = await ScrapeJob.prisma().create_many(
            data=[
                {
                    # data to create a ScrapeJob record
                    'linkedinUrls': Json({'cadfabfehe': True}),
                    'maxPosts': 368800899,
                },
                {
                    # data to create a ScrapeJob record
                    'linkedinUrls': Json({'bfaiacjjfc': True}),
                    'maxPosts': 486256185,
                },
            ],
            skip_duplicates=True,
        )
        ```
        """
        if self._client._active_provider == 'sqlite':
            raise errors.UnsupportedDatabaseError('sqlite', 'create_many()')

        resp = await self._client._execute(
            method='create_many',
            model=self._model,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )
        return int(resp['data']['result']['count'])

    async def delete(
        self,
        where: types.ScrapeJobWhereUniqueInput,
        include: Optional[types.ScrapeJobInclude] = None
    ) -> Optional[_PrismaModelT]:
        """Delete a single ScrapeJob record.

        Parameters
        ----------
        where
            ScrapeJob filter to select the record to be deleted, must be unique
        include
            Specifies which relations should be loaded on the returned ScrapeJob model

        Returns
        -------
        prisma.models.ScrapeJob
            The deleted ScrapeJob record
        None
            Could not find a record to delete

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        scrapejob = await ScrapeJob.prisma().delete(
            where={
                'id': 'bagcfbhiig',
            },
        )
        ```
        """
        try:
            resp = await self._client._execute(
                method='delete',
                model=self._model,
                arguments={
                    'where': where,
                    'include': include,
                },
            )
        except errors.RecordNotFoundError:
            return None

        return model_parse(self._model, resp['data']['result'])

    async def find_unique(
        self,
        where: types.ScrapeJobWhereUniqueInput,
        include: Optional[types.ScrapeJobInclude] = None
    ) -> Optional[_PrismaModelT]:
        """Find a unique ScrapeJob record.

        Parameters
        ----------
        where
            ScrapeJob filter to find the record, must be unique
        include
            Specifies which relations should be loaded on the returned ScrapeJob model

        Returns
        -------
        prisma.models.ScrapeJob
            The found ScrapeJob record
        None
            No record matching the given input could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        scrapejob = await ScrapeJob.prisma().find_unique(
            where={
                'id': 'cghideieh',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_unique',
            model=self._model,
            arguments={
                'where': where,
                'include': include,
            },
        )
        result = resp['data']['result']
        if result is None:
            return None
        return model_parse(self._model, result)

    async def find_unique_or_raise(
        self,
        where: types.ScrapeJobWhereUniqueInput,
        include: Optional[types.ScrapeJobInclude] = None
    ) -> _PrismaModelT:
        """Find a unique ScrapeJob record. Raises `RecordNotFoundError` if no record is found.

        Parameters
        ----------
        where
            ScrapeJob filter to find the record, must be unique
        include
            Specifies which relations should be loaded on the returned ScrapeJob model

        Returns
        -------
        prisma.models.ScrapeJob
            The found ScrapeJob record

        Raises
        ------
        prisma.errors.RecordNotFoundError
            No record was found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        scrapejob = await ScrapeJob.prisma().find_unique_or_raise(
            where={
                'id': 'biabhbdai',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_unique_or_raise',
            model=self._model,
            arguments={
                'where': where,
                'include': include,
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def find_many(
        self,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.ScrapeJobWhereInput] = None,
        cursor: Optional[types.ScrapeJobWhereUniqueInput] = None,
        include: Optional[types.ScrapeJobInclude] = None,
        order: Optional[Union[types.ScrapeJobOrderByInput, List[types.ScrapeJobOrderByInput]]] = None,
        distinct: Optional[List[types.ScrapeJobScalarFieldKeys]] = None,
    ) -> List[_PrismaModelT]:
        """Find multiple ScrapeJob records.

        An empty list is returned if no records could be found.

        Parameters
        ----------
        take
            Limit the maximum number of ScrapeJob records returned
        skip
            Ignore the first N results
        where
            ScrapeJob filter to select records
        cursor
            Specifies the position in the list to start returning results from, (typically an ID field)
        include
            Specifies which relations should be loaded on the returned ScrapeJob model
        order
            Order the returned ScrapeJob records by any field
        distinct
            Filter ScrapeJob records by either a single distinct field or distinct combinations of fields

        Returns
        -------
        List[prisma.models.ScrapeJob]
            The list of all ScrapeJob records that could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # find the first 10 ScrapeJob records
        scrapejobs = await ScrapeJob.prisma().find_many(take=10)

        # find the first 5 ScrapeJob records ordered by the linkedinUrls field
        scrapejobs = await ScrapeJob.prisma().find_many(
            take=5,
            order={
                'linkedinUrls': 'desc',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_many',
            model=self._model,
            arguments={
                'take': take,
                'skip': skip,
                'where': where,
                'order_by': order,
                'cursor': cursor,
                'include': include,
                'distinct': distinct,
            },
        )
        return [model_parse(self._model, r) for r in resp['data']['result']]

    async def find_first(
        self,
        skip: Optional[int] = None,
        where: Optional[types.ScrapeJobWhereInput] = None,
        cursor: Optional[types.ScrapeJobWhereUniqueInput] = None,
        include: Optional[types.ScrapeJobInclude] = None,
        order: Optional[Union[types.ScrapeJobOrderByInput, List[types.ScrapeJobOrderByInput]]] = None,
        distinct: Optional[List[types.ScrapeJobScalarFieldKeys]] = None,
    ) -> Optional[_PrismaModelT]:
        """Find a single ScrapeJob record.

        Parameters
        ----------
        skip
            Ignore the first N records
        where
            ScrapeJob filter to select the record
        cursor
            Specifies the position in the list to start returning results from, (typically an ID field)
        include
            Specifies which relations should be loaded on the returned ScrapeJob model
        order
            Order the returned ScrapeJob records by any field
        distinct
            Filter ScrapeJob records by either a single distinct field or distinct combinations of fields

        Returns
        -------
        prisma.models.ScrapeJob
            The first ScrapeJob record found, matching the given arguments
        None
            No record could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # find the second ScrapeJob record ordered by the maxPosts field
        scrapejob = await ScrapeJob.prisma().find_first(
            skip=1,
            order={
                'maxPosts': 'desc',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_first',
            model=self._model,
            arguments={
                'skip': skip,
                'where': where,
                'order_by': order,
                'cursor': cursor,
                'include': include,
                'distinct': distinct,
            },
        )
        result = resp['data']['result']
        if result is None:
            return None

        return model_parse(self._model, result)

    async def find_first_or_raise(
        self,
        skip: Optional[int] = None,
        where: Optional[types.ScrapeJobWhereInput] = None,
        cursor: Optional[types.ScrapeJobWhereUniqueInput] = None,
        include: Optional[types.ScrapeJobInclude] = None,
        order: Optional[Union[types.ScrapeJobOrderByInput, List[types.ScrapeJobOrderByInput]]] = None,
        distinct: Optional[List[types.ScrapeJobScalarFieldKeys]] = None,
    ) -> _PrismaModelT:
        """Find a single ScrapeJob record. Raises `RecordNotFoundError` if no record was found.

        Parameters
        ----------
        skip
            Ignore the first N records
        where
            ScrapeJob filter to select the record
        cursor
            Specifies the position in the list to start returning results from, (typically an ID field)
        include
            Specifies which relations should be loaded on the returned ScrapeJob model
        order
            Order the returned ScrapeJob records by any field
        distinct
            Filter ScrapeJob records by either a single distinct field or distinct combinations of fields

        Returns
        -------
        prisma.models.ScrapeJob
            The first ScrapeJob record found, matching the given arguments

        Raises
        ------
        prisma.errors.RecordNotFoundError
            No record was found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # find the second ScrapeJob record ordered by the apifyRunId field
        scrapejob = await ScrapeJob.prisma().find_first_or_raise(
            skip=1,
            order={
                'apifyRunId': 'desc',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_first_or_raise',
            model=self._model,
            arguments={
                'skip': skip,
                'where': where,
                'order_by': order,
                'cursor': cursor,
                'include': include,
                'distinct': distinct,
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def update(
        self,
        data: types.ScrapeJobUpdateInput,
        where: types.ScrapeJobWhereUniqueInput,
        include: Optional[types.ScrapeJobInclude] = None
    ) -> Optional[_PrismaModelT]:
        """Update a single ScrapeJob record.

        Parameters
        ----------
        data
            ScrapeJob record data specifying what to update
        where
            ScrapeJob filter to select the unique record to create / update
        include
            Specifies which relations should be loaded on the returned ScrapeJob model

        Returns
        -------
        prisma.models.ScrapeJob
            The updated ScrapeJob record
        None
            No record could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        scrapejob = await ScrapeJob.prisma().update(
            where={
                'id': 'idghgaicb',
            },
            data={
                # data to update the ScrapeJob record to
            },
        )
        ```
        """
        try:
            resp = await self._client._execute(
                method='update',
                model=self._model,
                arguments={
                    'data': data,
                    'where': where,
                    'include': include,
                },
            )
        except errors.RecordNotFoundError:
            return None

        return model_parse(self._model, resp['data']['result'])

    async def upsert(
        self,
        where: types.ScrapeJobWhereUniqueInput,
        data: types.ScrapeJobUpsertInput,
        include: Optional[types.ScrapeJobInclude] = None,
    ) -> _PrismaModelT:
        """Updates an existing record or create a new one

        Parameters
        ----------
        where
            ScrapeJob filter to select the unique record to create / update
        data
            Data specifying what fields to set on create and update
        include
            Specifies which relations should be loaded on the returned ScrapeJob model

        Returns
        -------
        prisma.models.ScrapeJob
            The created or updated ScrapeJob record

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        scrapejob = await ScrapeJob.prisma().upsert(
            where={
                'id': 'fjfddhigg',
            },
            data={
                'create': {
                    'id': 'fjfddhigg',
                    'linkedinUrls': Json({'bfaiacjjfc': True}),
                    'maxPosts': 486256185,
                },
                'update': {
                    'linkedinUrls': Json({'bfaiacjjfc': True}),
                    'maxPosts': 486256185,
                },
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='upsert',
            model=self._model,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def update_many(
        self,
        data: types.ScrapeJobUpdateManyMutationInput,
        where: types.ScrapeJobWhereInput,
    ) -> int:
        """Update multiple ScrapeJob records

        Parameters
        ----------
        data
            ScrapeJob data to update the selected ScrapeJob records to
        where
            Filter to select the ScrapeJob records to update

        Returns
        -------
        int
            The total number of ScrapeJob records that were updated

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # update all ScrapeJob records
        total = await ScrapeJob.prisma().update_many(
            data={
                'result': Json({'hjaecfifb': True})
            },
            where={}
        )
        ```
        """
        resp = await self._client._execute(
            method='update_many',
            model=self._model,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )
        return int(resp['data']['result']['count'])

    @overload
    async def count(
        self,
        select: None = None,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.ScrapeJobWhereInput] = None,
        cursor: Optional[types.ScrapeJobWhereUniqueInput] = None,
    ) -> int:
        """Count the number of ScrapeJob records present in the database

        Parameters
        ----------
        select
            Select the ScrapeJob fields to be counted
        take
            Limit the maximum result
        skip
            Ignore the first N records
        where
            ScrapeJob filter to find records
        cursor
            Specifies the position in the list to start counting results from, (typically an ID field)
        order
            This parameter is deprecated and will be removed in a future release

        Returns
        -------
        int
            The total number of records found, returned if `select` is not given

        prisma.types.ScrapeJobCountAggregateOutput
            Data returned when `select` is used, the fields present in this dictionary will
            match the fields passed in the `select` argument

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # total: int
        total = await ScrapeJob.prisma().count()

        # results: prisma.types.ScrapeJobCountAggregateOutput
        results = await ScrapeJob.prisma().count(
            select={
                '_all': True,
                'error': True,
            },
        )
        ```
        """


    @overload
    async def count(
        self,
        select: types.ScrapeJobCountAggregateInput,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.ScrapeJobWhereInput] = None,
        cursor: Optional[types.ScrapeJobWhereUniqueInput] = None,
    ) -> types.ScrapeJobCountAggregateOutput:
        ...

    async def count(
        self,
        select: Optional[types.ScrapeJobCountAggregateInput] = None,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.ScrapeJobWhereInput] = None,
        cursor: Optional[types.ScrapeJobWhereUniqueInput] = None,
    ) -> Union[int, types.ScrapeJobCountAggregateOutput]:
        """Count the number of ScrapeJob records present in the database

        Parameters
        ----------
        select
            Select the ScrapeJob fields to be counted
        take
            Limit the maximum result
        skip
            Ignore the first N records
        where
            ScrapeJob filter to find records
        cursor
            Specifies the position in the list to start counting results from, (typically an ID field)
        order
            This parameter is deprecated and will be removed in a future release

        Returns
        -------
        int
            The total number of records found, returned if `select` is not given

        prisma.types.ScrapeJobCountAggregateOutput
            Data returned when `select` is used, the fields present in this dictionary will
            match the fields passed in the `select` argument

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # total: int
        total = await ScrapeJob.prisma().count()

        # results: prisma.types.ScrapeJobCountAggregateOutput
        results = await ScrapeJob.prisma().count(
            select={
                '_all': True,
                'createdAt': True,
            },
        )
        ```
        """

        # TODO: this selection building should be moved to the QueryBuilder
        #
        # note the distinction between checking for `not select` here and `select is None`
        # later is to handle the case that the given select dictionary is empty, this
        # is a limitation of our types.
        if not select:
            root_selection = ['_count { _all }']
        else:

            root_selection = [
                '_count {{ {0} }}'.format(' '.join(k for k, v in select.items() if v is True))
            ]

        resp = await self._client._execute(
            method='count',
            model=self._model,
            arguments={
                'take': take,
                'skip': skip,
                'where': where,
                'cursor': cursor,
            },
            root_selection=root_selection,
        )

        if select is None:
            return cast(int, resp['data']['result']['_count']['_all'])
        else:
            return cast(types.ScrapeJobCountAggregateOutput, resp['data']['result']['_count'])

    async def delete_many(
        self,
        where: Optional[types.ScrapeJobWhereInput] = None
    ) -> int:
        """Delete multiple ScrapeJob records.

        Parameters
        ----------
        where
            Optional ScrapeJob filter to find the records to be deleted

        Returns
        -------
        int
            The total number of ScrapeJob records that were deleted

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # delete all ScrapeJob records
        total = await ScrapeJob.prisma().delete_many()
        ```
        """
        resp = await self._client._execute(
            method='delete_many',
            model=self._model,
            arguments={'where': where},
            root_selection=['count'],
        )
        return int(resp['data']['result']['count'])

    # TODO: make this easier to work with safely, currently output fields are typed as
    #       not required, we should refactor the return type
    # TODO: consider returning a Dict where the keys are a Tuple of the `by` selection
    # TODO: statically type that the order argument is required when take or skip are present
    async def group_by(
        self,
        by: List['types.ScrapeJobScalarFieldKeys'],
        *,
        where: Optional['types.ScrapeJobWhereInput'] = None,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        avg: Optional['types.ScrapeJobAvgAggregateInput'] = None,
        sum: Optional['types.ScrapeJobSumAggregateInput'] = None,
        min: Optional['types.ScrapeJobMinAggregateInput'] = None,
        max: Optional['types.ScrapeJobMaxAggregateInput'] = None,
        having: Optional['types.ScrapeJobScalarWhereWithAggregatesInput'] = None,
        count: Optional[Union[bool, 'types.ScrapeJobCountAggregateInput']] = None,
        order: Optional[Union[Mapping['types.ScrapeJobScalarFieldKeys', 'types.SortOrder'], List[Mapping['types.ScrapeJobScalarFieldKeys', 'types.SortOrder']]]] = None,
    ) -> List['types.ScrapeJobGroupByOutput']:
        """Group ScrapeJob records by one or more field values and perform aggregations
        each group such as finding the average.

        Parameters
        ----------
        by
            List of scalar ScrapeJob fields to group records by
        where
            ScrapeJob filter to select records
        take
            Limit the maximum number of ScrapeJob records returned
        skip
            Ignore the first N records
        avg
            Adds the average of all values of the specified fields to the `_avg` field
            in the returned data.
        sum
            Adds the sum of all values of the specified fields to the `_sum` field
            in the returned data.
        min
            Adds the smallest available value for the specified fields to the `_min` field
            in the returned data.
        max
            Adds the largest available value for the specified fields to the `_max` field
            in the returned data.
        count
            Adds a count of non-fields to the `_count` field in the returned data.
        having
            Allows you to filter groups by an aggregate value - for example only return
            groups having an average age less than 50.
        order
            Lets you order the returned list by any property that is also present in `by`.
            Only **one** field is allowed at a time.

        Returns
        -------
        List[prisma.types.ScrapeJobGroupByOutput]
            A list of dictionaries representing the ScrapeJob record,
            this will also have additional fields present if aggregation arguments
            are used (see the above parameters)

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # group ScrapeJob records by updatedAt values
        # and count how many records are in each group
        results = await ScrapeJob.prisma().group_by(
            ['updatedAt'],
            count=True,
        )
        ```
        """
        if order is None:
            if take is not None:
                raise TypeError('Missing argument: \'order\' which is required when \'take\' is present')

            if skip is not None:
                raise TypeError('Missing argument: \'order\' which is required when \'skip\' is present')

        root_selection: List[str] = [*by]
        if avg is not None:
            root_selection.append(_select_fields('_avg', avg))

        if min is not None:
            root_selection.append(_select_fields('_min', min))

        if sum is not None:
            root_selection.append(_select_fields('_sum', sum))

        if max is not None:
            root_selection.append(_select_fields('_max', max))

        if count is not None:
            if count is True:
                root_selection.append('_count { _all }')
            elif isinstance(count, dict):
                root_selection.append(_select_fields('_count', count))

        resp = await self._client._execute(
            method='group_by',
            model=self._model,
            arguments={
                'by': by,
                'take': take,
                'skip': skip,
                'where': where,
                'having': having,
                'orderBy': order,
            },
            root_selection=root_selection,
        )
        return resp['data']['result']  # type: ignore[no-any-return]


class SearchQueryActions(Generic[_PrismaModelT]):
    __slots__ = (
        '_client',
        '_model',
    )

    def __init__(self, client: 'Client', model: Type[_PrismaModelT]) -> None:
        self._client = client
        self._model = model

    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
    ) -> List[_PrismaModelT]:
        """Execute a raw SQL query

        Parameters
        ----------
        query
            The raw SQL query string to be executed
        *args
            Parameters to be passed to the SQL query, these MUST be used over
            string formatting to avoid an SQL injection vulnerability

        Returns
        -------
        List[prisma.models.SearchQuery]
            The records returned by the SQL query

        Raises
        ------
        prisma_errors.RawQueryError
            This could be due to invalid syntax, mismatched number of parameters or any other error
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        users = await SearchQuery.prisma().query_raw(
            'SELECT * FROM SearchQuery WHERE id = $1',
            'cbbbjbfcii',
        )
        ```
        """
        return await self._client.query_raw(query, *args, model=self._model)

    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
    ) -> Optional[_PrismaModelT]:
        """Execute a raw SQL query, returning the first result

        Parameters
        ----------
        query
            The raw SQL query string to be executed
        *args
            Parameters to be passed to the SQL query, these MUST be used over
            string formatting to avoid an SQL injection vulnerability

        Returns
        -------
        prisma.models.SearchQuery
            The first record returned by the SQL query
        None
            The raw SQL query did not return any records

        Raises
        ------
        prisma_errors.RawQueryError
            This could be due to invalid syntax, mismatched number of parameters or any other error
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        user = await SearchQuery.prisma().query_first(
            'SELECT * FROM SearchQuery WHERE filters = $1',
            Json({'bbejhfidcb': True}),
        )
        ```
        """
        return await self._client.query_first(query, *args, model=self._model)

    async def create(
        self,
        data: types.SearchQueryCreateInput,
        include: Optional[types.SearchQueryInclude] = None
    ) -> _PrismaModelT:
        """Create a new SearchQuery record.

        Parameters
        ----------
        data
            SearchQuery record data
        include
            Specifies which relations should be loaded on the returned SearchQuery model

        Returns
        -------
        prisma.models.SearchQuery
            The created SearchQuery record

        Raises
        ------
        prisma.errors.MissingRequiredValueError
            Value is required but was not found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # create a SearchQuery record from just the required fields
        searchquery = await SearchQuery.prisma().create(
            data={
                # data to create a SearchQuery record
                'filters': Json({'bgeecijdgg': True}),
                'sqlQuery': 'bdiicjafbj',
                'resultCount': 1647418052,
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='create',
            model=self._model,
            arguments={
                'data': data,
                'include': include,
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def create_many(
        self,
        data: List[types.SearchQueryCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> int:
        """Create multiple SearchQuery records at once.

        This function is *not* available when using SQLite.

        Parameters
        ----------
        data
            List of SearchQuery record data
        skip_duplicates
            Boolean flag for ignoring unique constraint errors

        Returns
        -------
        int
            The total number of records created

        Raises
        ------
        prisma.errors.UnsupportedDatabaseError
            Attempting to query when using SQLite
        prisma.errors.UniqueViolationError
            A unique constraint check has failed, these can be ignored with the `skip_duplicates` argument
        prisma.errors.MissingRequiredValueError
            Value is required but was not found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        total = await SearchQuery.prisma().create_many(
            data=[
                {
                    # data to create a SearchQuery record
                    'filters': Json({'bghffegacj': True}),
                    'sqlQuery': 'bhghchehcc',
                    'resultCount': 326272115,
                },
                {
                    # data to create a SearchQuery record
                    'filters': Json({'bdedcabahc': True}),
                    'sqlQuery': 'ghfhiafcb',
                    'resultCount': 744964398,
                },
            ],
            skip_duplicates=True,
        )
        ```
        """
        if self._client._active_provider == 'sqlite':
            raise errors.UnsupportedDatabaseError('sqlite', 'create_many()')

        resp = await self._client._execute(
            method='create_many',
            model=self._model,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )
        return int(resp['data']['result']['count'])

    async def delete(
        self,
        where: types.SearchQueryWhereUniqueInput,
        include: Optional[types.SearchQueryInclude] = None
    ) -> Optional[_PrismaModelT]:
        """Delete a single SearchQuery record.

        Parameters
        ----------
        where
            SearchQuery filter to select the record to be deleted, must be unique
        include
            Specifies which relations should be loaded on the returned SearchQuery model

        Returns
        -------
        prisma.models.SearchQuery
            The deleted SearchQuery record
        None
            Could not find a record to delete

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        searchquery = await SearchQuery.prisma().delete(
            where={
                'id': 'bjgjgibgbf',
            },
        )
        ```
        """
        try:
            resp = await self._client._execute(
                method='delete',
                model=self._model,
                arguments={
                    'where': where,
                    'include': include,
                },
            )
        except errors.RecordNotFoundError:
            return None

        return model_parse(self._model, resp['data']['result'])

    async def find_unique(
        self,
        where: types.SearchQueryWhereUniqueInput,
        include: Optional[types.SearchQueryInclude] = None
    ) -> Optional[_PrismaModelT]:
        """Find a unique SearchQuery record.

        Parameters
        ----------
        where
            SearchQuery filter to find the record, must be unique
        include
            Specifies which relations should be loaded on the returned SearchQuery model

        Returns
        -------
        prisma.models.SearchQuery
            The found SearchQuery record
        None
            No record matching the given input could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        searchquery = await SearchQuery.prisma().find_unique(
            where={
                'id': 'bbbgbhfjge',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_unique',
            model=self._model,
            arguments={
                'where': where,
                'include': include,
            },
        )
        result = resp['data']['result']
        if result is None:
            return None
        return model_parse(self._model, result)

    async def find_unique_or_raise(
        self,
        where: types.SearchQueryWhereUniqueInput,
        include: Optional[types.SearchQueryInclude] = None
    ) -> _PrismaModelT:
        """Find a unique SearchQuery record. Raises `RecordNotFoundError` if no record is found.

        Parameters
        ----------
        where
            SearchQuery filter to find the record, must be unique
        include
            Specifies which relations should be loaded on the returned SearchQuery model

        Returns
        -------
        prisma.models.SearchQuery
            The found SearchQuery record

        Raises
        ------
        prisma.errors.RecordNotFoundError
            No record was found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        searchquery = await SearchQuery.prisma().find_unique_or_raise(
            where={
                'id': 'igbehcbab',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_unique_or_raise',
            model=self._model,
            arguments={
                'where': where,
                'include': include,
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def find_many(
        self,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.SearchQueryWhereInput] = None,
        cursor: Optional[types.SearchQueryWhereUniqueInput] = None,
        include: Optional[types.SearchQueryInclude] = None,
        order: Optional[Union[types.SearchQueryOrderByInput, List[types.SearchQueryOrderByInput]]] = None,
        distinct: Optional[List[types.SearchQueryScalarFieldKeys]] = None,
    ) -> List[_PrismaModelT]:
        """Find multiple SearchQuery records.

        An empty list is returned if no records could be found.

        Parameters
        ----------
        take
            Limit the maximum number of SearchQuery records returned
        skip
            Ignore the first N results
        where
            SearchQuery filter to select records
        cursor
            Specifies the position in the list to start returning results from, (typically an ID field)
        include
            Specifies which relations should be loaded on the returned SearchQuery model
        order
            Order the returned SearchQuery records by any field
        distinct
            Filter SearchQuery records by either a single distinct field or distinct combinations of fields

        Returns
        -------
        List[prisma.models.SearchQuery]
            The list of all SearchQuery records that could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # find the first 10 SearchQuery records
        searchquerys = await SearchQuery.prisma().find_many(take=10)

        # find the first 5 SearchQuery records ordered by the sqlQuery field
        searchquerys = await SearchQuery.prisma().find_many(
            take=5,
            order={
                'sqlQuery': 'desc',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_many',
            model=self._model,
            arguments={
                'take': take,
                'skip': skip,
                'where': where,
                'order_by': order,
                'cursor': cursor,
                'include': include,
                'distinct': distinct,
            },
        )
        return [model_parse(self._model, r) for r in resp['data']['result']]

    async def find_first(
        self,
        skip: Optional[int] = None,
        where: Optional[types.SearchQueryWhereInput] = None,
        cursor: Optional[types.SearchQueryWhereUniqueInput] = None,
        include: Optional[types.SearchQueryInclude] = None,
        order: Optional[Union[types.SearchQueryOrderByInput, List[types.SearchQueryOrderByInput]]] = None,
        distinct: Optional[List[types.SearchQueryScalarFieldKeys]] = None,
    ) -> Optional[_PrismaModelT]:
        """Find a single SearchQuery record.

        Parameters
        ----------
        skip
            Ignore the first N records
        where
            SearchQuery filter to select the record
        cursor
            Specifies the position in the list to start returning results from, (typically an ID field)
        include
            Specifies which relations should be loaded on the returned SearchQuery model
        order
            Order the returned SearchQuery records by any field
        distinct
            Filter SearchQuery records by either a single distinct field or distinct combinations of fields

        Returns
        -------
        prisma.models.SearchQuery
            The first SearchQuery record found, matching the given arguments
        None
            No record could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # find the second SearchQuery record ordered by the resultCount field
        searchquery = await SearchQuery.prisma().find_first(
            skip=1,
            order={
                'resultCount': 'desc',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_first',
            model=self._model,
            arguments={
                'skip': skip,
                'where': where,
                'order_by': order,
                'cursor': cursor,
                'include': include,
                'distinct': distinct,
            },
        )
        result = resp['data']['result']
        if result is None:
            return None

        return model_parse(self._model, result)

    async def find_first_or_raise(
        self,
        skip: Optional[int] = None,
        where: Optional[types.SearchQueryWhereInput] = None,
        cursor: Optional[types.SearchQueryWhereUniqueInput] = None,
        include: Optional[types.SearchQueryInclude] = None,
        order: Optional[Union[types.SearchQueryOrderByInput, List[types.SearchQueryOrderByInput]]] = None,
        distinct: Optional[List[types.SearchQueryScalarFieldKeys]] = None,
    ) -> _PrismaModelT:
        """Find a single SearchQuery record. Raises `RecordNotFoundError` if no record was found.

        Parameters
        ----------
        skip
            Ignore the first N records
        where
            SearchQuery filter to select the record
        cursor
            Specifies the position in the list to start returning results from, (typically an ID field)
        include
            Specifies which relations should be loaded on the returned SearchQuery model
        order
            Order the returned SearchQuery records by any field
        distinct
            Filter SearchQuery records by either a single distinct field or distinct combinations of fields

        Returns
        -------
        prisma.models.SearchQuery
            The first SearchQuery record found, matching the given arguments

        Raises
        ------
        prisma.errors.RecordNotFoundError
            No record was found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # find the second SearchQuery record ordered by the createdAt field
        searchquery = await SearchQuery.prisma().find_first_or_raise(
            skip=1,
            order={
                'createdAt': 'desc',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_first_or_raise',
            model=self._model,
            arguments={
                'skip': skip,
                'where': where,
                'order_by': order,
                'cursor': cursor,
                'include': include,
                'distinct': distinct,
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def update(
        self,
        data: types.SearchQueryUpdateInput,
        where: types.SearchQueryWhereUniqueInput,
        include: Optional[types.SearchQueryInclude] = None
    ) -> Optional[_PrismaModelT]:
        """Update a single SearchQuery record.

        Parameters
        ----------
        data
            SearchQuery record data specifying what to update
        where
            SearchQuery filter to select the unique record to create / update
        include
            Specifies which relations should be loaded on the returned SearchQuery model

        Returns
        -------
        prisma.models.SearchQuery
            The updated SearchQuery record
        None
            No record could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        searchquery = await SearchQuery.prisma().update(
            where={
                'id': 'bdadaadhag',
            },
            data={
                # data to update the SearchQuery record to
            },
        )
        ```
        """
        try:
            resp = await self._client._execute(
                method='update',
                model=self._model,
                arguments={
                    'data': data,
                    'where': where,
                    'include': include,
                },
            )
        except errors.RecordNotFoundError:
            return None

        return model_parse(self._model, resp['data']['result'])

    async def upsert(
        self,
        where: types.SearchQueryWhereUniqueInput,
        data: types.SearchQueryUpsertInput,
        include: Optional[types.SearchQueryInclude] = None,
    ) -> _PrismaModelT:
        """Updates an existing record or create a new one

        Parameters
        ----------
        where
            SearchQuery filter to select the unique record to create / update
        data
            Data specifying what fields to set on create and update
        include
            Specifies which relations should be loaded on the returned SearchQuery model

        Returns
        -------
        prisma.models.SearchQuery
            The created or updated SearchQuery record

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        searchquery = await SearchQuery.prisma().upsert(
            where={
                'id': 'bgiggdidbf',
            },
            data={
                'create': {
                    'id': 'bgiggdidbf',
                    'filters': Json({'bdedcabahc': True}),
                    'sqlQuery': 'ghfhiafcb',
                    'resultCount': 744964398,
                },
                'update': {
                    'filters': Json({'bdedcabahc': True}),
                    'sqlQuery': 'ghfhiafcb',
                    'resultCount': 744964398,
                },
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='upsert',
            model=self._model,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def update_many(
        self,
        data: types.SearchQueryUpdateManyMutationInput,
        where: types.SearchQueryWhereInput,
    ) -> int:
        """Update multiple SearchQuery records

        Parameters
        ----------
        data
            SearchQuery data to update the selected SearchQuery records to
        where
            Filter to select the SearchQuery records to update

        Returns
        -------
        int
            The total number of SearchQuery records that were updated

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # update all SearchQuery records
        total = await SearchQuery.prisma().update_many(
            data={
                'id': 'caaaedabfc'
            },
            where={}
        )
        ```
        """
        resp = await self._client._execute(
            method='update_many',
            model=self._model,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )
        return int(resp['data']['result']['count'])

    @overload
    async def count(
        self,
        select: None = None,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.SearchQueryWhereInput] = None,
        cursor: Optional[types.SearchQueryWhereUniqueInput] = None,
    ) -> int:
        """Count the number of SearchQuery records present in the database

        Parameters
        ----------
        select
            Select the SearchQuery fields to be counted
        take
            Limit the maximum result
        skip
            Ignore the first N records
        where
            SearchQuery filter to find records
        cursor
            Specifies the position in the list to start counting results from, (typically an ID field)
        order
            This parameter is deprecated and will be removed in a future release

        Returns
        -------
        int
            The total number of records found, returned if `select` is not given

        prisma.types.SearchQueryCountAggregateOutput
            Data returned when `select` is used, the fields present in this dictionary will
            match the fields passed in the `select` argument

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # total: int
        total = await SearchQuery.prisma().count()

        # results: prisma.types.SearchQueryCountAggregateOutput
        results = await SearchQuery.prisma().count(
            select={
                '_all': True,
                'filters': True,
            },
        )
        ```
        """


    @overload
    async def count(
        self,
        select: types.SearchQueryCountAggregateInput,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.SearchQueryWhereInput] = None,
        cursor: Optional[types.SearchQueryWhereUniqueInput] = None,
    ) -> types.SearchQueryCountAggregateOutput:
        ...

    async def count(
        self,
        select: Optional[types.SearchQueryCountAggregateInput] = None,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.SearchQueryWhereInput] = None,
        cursor: Optional[types.SearchQueryWhereUniqueInput] = None,
    ) -> Union[int, types.SearchQueryCountAggregateOutput]:
        """Count the number of SearchQuery records present in the database

        Parameters
        ----------
        select
            Select the SearchQuery fields to be counted
        take
            Limit the maximum result
        skip
            Ignore the first N records
        where
            SearchQuery filter to find records
        cursor
            Specifies the position in the list to start counting results from, (typically an ID field)
        order
            This parameter is deprecated and will be removed in a future release

        Returns
        -------
        int
            The total number of records found, returned if `select` is not given

        prisma.types.SearchQueryCountAggregateOutput
            Data returned when `select` is used, the fields present in this dictionary will
            match the fields passed in the `select` argument

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # total: int
        total = await SearchQuery.prisma().count()

        # results: prisma.types.SearchQueryCountAggregateOutput
        results = await SearchQuery.prisma().count(
            select={
                '_all': True,
                'sqlQuery': True,
            },
        )
        ```
        """

        # TODO: this selection building should be moved to the QueryBuilder
        #
        # note the distinction between checking for `not select` here and `select is None`
        # later is to handle the case that the given select dictionary is empty, this
        # is a limitation of our types.
        if not select:
            root_selection = ['_count { _all }']
        else:

            root_selection = [
                '_count {{ {0} }}'.format(' '.join(k for k, v in select.items() if v is True))
            ]

        resp = await self._client._execute(
            method='count',
            model=self._model,
            arguments={
                'take': take,
                'skip': skip,
                'where': where,
                'cursor': cursor,
            },
            root_selection=root_selection,
        )

        if select is None:
            return cast(int, resp['data']['result']['_count']['_all'])
        else:
            return cast(types.SearchQueryCountAggregateOutput, resp['data']['result']['_count'])

    async def delete_many(
        self,
        where: Optional[types.SearchQueryWhereInput] = None
    ) -> int:
        """Delete multiple SearchQuery records.

        Parameters
        ----------
        where
            Optional SearchQuery filter to find the records to be deleted

        Returns
        -------
        int
            The total number of SearchQuery records that were deleted

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # delete all SearchQuery records
        total = await SearchQuery.prisma().delete_many()
        ```
        """
        resp = await self._client._execute(
            method='delete_many',
            model=self._model,
            arguments={'where': where},
            root_selection=['count'],
        )
        return int(resp['data']['result']['count'])

    # TODO: make this easier to work with safely, currently output fields are typed as
    #       not required, we should refactor the return type
    # TODO: consider returning a Dict where the keys are a Tuple of the `by` selection
    # TODO: statically type that the order argument is required when take or skip are present
    async def group_by(
        self,
        by: List['types.SearchQueryScalarFieldKeys'],
        *,
        where: Optional['types.SearchQueryWhereInput'] = None,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        avg: Optional['types.SearchQueryAvgAggregateInput'] = None,
        sum: Optional['types.SearchQuerySumAggregateInput'] = None,
        min: Optional['types.SearchQueryMinAggregateInput'] = None,
        max: Optional['types.SearchQueryMaxAggregateInput'] = None,
        having: Optional['types.SearchQueryScalarWhereWithAggregatesInput'] = None,
        count: Optional[Union[bool, 'types.SearchQueryCountAggregateInput']] = None,
        order: Optional[Union[Mapping['types.SearchQueryScalarFieldKeys', 'types.SortOrder'], List[Mapping['types.SearchQueryScalarFieldKeys', 'types.SortOrder']]]] = None,
    ) -> List['types.SearchQueryGroupByOutput']:
        """Group SearchQuery records by one or more field values and perform aggregations
        each group such as finding the average.

        Parameters
        ----------
        by
            List of scalar SearchQuery fields to group records by
        where
            SearchQuery filter to select records
        take
            Limit the maximum number of SearchQuery records returned
        skip
            Ignore the first N records
        avg
            Adds the average of all values of the specified fields to the `_avg` field
            in the returned data.
        sum
            Adds the sum of all values of the specified fields to the `_sum` field
            in the returned data.
        min
            Adds the smallest available value for the specified fields to the `_min` field
            in the returned data.
        max
            Adds the largest available value for the specified fields to the `_max` field
            in the returned data.
        count
            Adds a count of non-fields to the `_count` field in the returned data.
        having
            Allows you to filter groups by an aggregate value - for example only return
            groups having an average age less than 50.
        order
            Lets you order the returned list by any property that is also present in `by`.
            Only **one** field is allowed at a time.

        Returns
        -------
        List[prisma.types.SearchQueryGroupByOutput]
            A list of dictionaries representing the SearchQuery record,
            this will also have additional fields present if aggregation arguments
            are used (see the above parameters)

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # group SearchQuery records by resultCount values
        # and count how many records are in each group
        results = await SearchQuery.prisma().group_by(
            ['resultCount'],
            count=True,
        )
        ```
        """
        if order is None:
            if take is not None:
                raise TypeError('Missing argument: \'order\' which is required when \'take\' is present')

            if skip is not None:
                raise TypeError('Missing argument: \'order\' which is required when \'skip\' is present')

        root_selection: List[str] = [*by]
        if avg is not None:
            root_selection.append(_select_fields('_avg', avg))

        if min is not None:
            root_selection.append(_select_fields('_min', min))

        if sum is not None:
            root_selection.append(_select_fields('_sum', sum))

        if max is not None:
            root_selection.append(_select_fields('_max', max))

        if count is not None:
            if count is True:
                root_selection.append('_count { _all }')
            elif isinstance(count, dict):
                root_selection.append(_select_fields('_count', count))

        resp = await self._client._execute(
            method='group_by',
            model=self._model,
            arguments={
                'by': by,
                'take': take,
                'skip': skip,
                'where': where,
                'having': having,
                'orderBy': order,
            },
            root_selection=root_selection,
        )
        return resp['data']['result']  # type: ignore[no-any-return]



def _select_fields(root: str, select: Mapping[str, Any]) -> str:
    """Helper to build a GraphQL selection string

    This is a work around until field selection is added to the query builder.
    """

    return root + ' {{ {0} }}'.format(' '.join(k for k, v in select.items() if v is True))


from . import models