# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template types.py.jinja --
from typing import TypeVar

import httpx
from .utils import _NoneType



# TODO: filters with aggregates should have their own recursive fields
# TODO: cleanup whitespace control
# TODO: add an argument to signify that the last iteration should be skipped


SortMode = Literal['default', 'insensitive']
SortOrder = Literal['asc', 'desc']

MetricsFormat = Literal['json', 'prometheus']


class _DatasourceOverrideOptional(TypedDict, total=False):
    env: str
    name: str


class DatasourceOverride(_DatasourceOverrideOptional):
    url: str


# NOTE: we don't support some options as their type hints are not publicly exposed
# https://github.com/encode/httpx/discussions/1977
class HttpConfig(TypedDict, total=False):
    app: Callable[[Mapping[str, Any], Any], Any]
    http1: bool
    http2: bool
    limits: httpx.Limits
    timeout: Union[None, float, httpx.Timeout]
    trust_env: bool
    max_redirects: int


# types that can be serialized to json by our query builder
Serializable = Union[
    None,
    bool,
    float,
    int,
    str,
    datetime.datetime,
    List[Any],
    Dict[None, Any],
    Dict[bool, Any],
    Dict[float, Any],
    Dict[int, Any],
    Dict[str, Any],
]


    

StringFilter = TypedDict(
    'StringFilter',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
        'not': Union[str, 'StringFilterRecursive1'],
        'mode': SortMode,
    },
    total=False,
)


StringFilterRecursive1 = TypedDict(
    'StringFilterRecursive1',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
        'not': Union[str, 'StringFilterRecursive2'],
        'mode': SortMode,
    },
    total=False,
)


StringFilterRecursive2 = TypedDict(
    'StringFilterRecursive2',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
        'not': Union[str, 'StringFilterRecursive3'],
        'mode': SortMode,
    },
    total=False,
)


StringFilterRecursive3 = TypedDict(
    'StringFilterRecursive3',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
        'not': Union[str, 'StringFilterRecursive4'],
        'mode': SortMode,
    },
    total=False,
)


StringFilterRecursive4 = TypedDict(
    'StringFilterRecursive4',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
                'mode': SortMode,
    },
    total=False,
)


class StringWithAggregatesFilter(StringFilter, total=False):
    _max: 'StringFilter'
    _min: 'StringFilter'
    _sum: 'StringFilter'
    _avg: 'StringFilter'
    _count: 'IntFilter'


    

DateTimeFilter = TypedDict(
    'DateTimeFilter',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
        'not': Union[datetime.datetime, 'DateTimeFilterRecursive1'],
    },
    total=False,
)


DateTimeFilterRecursive1 = TypedDict(
    'DateTimeFilterRecursive1',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
        'not': Union[datetime.datetime, 'DateTimeFilterRecursive2'],
    },
    total=False,
)


DateTimeFilterRecursive2 = TypedDict(
    'DateTimeFilterRecursive2',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
        'not': Union[datetime.datetime, 'DateTimeFilterRecursive3'],
    },
    total=False,
)


DateTimeFilterRecursive3 = TypedDict(
    'DateTimeFilterRecursive3',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
        'not': Union[datetime.datetime, 'DateTimeFilterRecursive4'],
    },
    total=False,
)


DateTimeFilterRecursive4 = TypedDict(
    'DateTimeFilterRecursive4',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
            },
    total=False,
)


class DateTimeWithAggregatesFilter(DateTimeFilter, total=False):
    _max: 'DateTimeFilter'
    _min: 'DateTimeFilter'
    _sum: 'DateTimeFilter'
    _avg: 'DateTimeFilter'
    _count: 'IntFilter'


    

BooleanFilter = TypedDict(
    'BooleanFilter',
    {
        'equals': bool,
        'not': Union[bool, 'BooleanFilterRecursive1'],
    },
    total=False,
)


BooleanFilterRecursive1 = TypedDict(
    'BooleanFilterRecursive1',
    {
        'equals': bool,
        'not': Union[bool, 'BooleanFilterRecursive2'],
    },
    total=False,
)


BooleanFilterRecursive2 = TypedDict(
    'BooleanFilterRecursive2',
    {
        'equals': bool,
        'not': Union[bool, 'BooleanFilterRecursive3'],
    },
    total=False,
)


BooleanFilterRecursive3 = TypedDict(
    'BooleanFilterRecursive3',
    {
        'equals': bool,
        'not': Union[bool, 'BooleanFilterRecursive4'],
    },
    total=False,
)


BooleanFilterRecursive4 = TypedDict(
    'BooleanFilterRecursive4',
    {
        'equals': bool,
            },
    total=False,
)


class BooleanWithAggregatesFilter(BooleanFilter, total=False):
    _max: 'BooleanFilter'
    _min: 'BooleanFilter'
    _sum: 'BooleanFilter'
    _avg: 'BooleanFilter'
    _count: 'IntFilter'


    

IntFilter = TypedDict(
    'IntFilter',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
        'not': Union[int, 'IntFilterRecursive1'],
    },
    total=False,
)


IntFilterRecursive1 = TypedDict(
    'IntFilterRecursive1',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
        'not': Union[int, 'IntFilterRecursive2'],
    },
    total=False,
)


IntFilterRecursive2 = TypedDict(
    'IntFilterRecursive2',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
        'not': Union[int, 'IntFilterRecursive3'],
    },
    total=False,
)


IntFilterRecursive3 = TypedDict(
    'IntFilterRecursive3',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
        'not': Union[int, 'IntFilterRecursive4'],
    },
    total=False,
)


IntFilterRecursive4 = TypedDict(
    'IntFilterRecursive4',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
            },
    total=False,
)


class IntWithAggregatesFilter(IntFilter, total=False):
    _max: 'IntFilter'
    _min: 'IntFilter'
    _sum: 'IntFilter'
    _avg: 'IntFilter'
    _count: 'IntFilter'


BigIntFilter = IntFilter
BigIntWithAggregatesFilter = IntWithAggregatesFilter
    

FloatFilter = TypedDict(
    'FloatFilter',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
        'not': Union[float, 'FloatFilterRecursive1'],
    },
    total=False,
)


FloatFilterRecursive1 = TypedDict(
    'FloatFilterRecursive1',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
        'not': Union[float, 'FloatFilterRecursive2'],
    },
    total=False,
)


FloatFilterRecursive2 = TypedDict(
    'FloatFilterRecursive2',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
        'not': Union[float, 'FloatFilterRecursive3'],
    },
    total=False,
)


FloatFilterRecursive3 = TypedDict(
    'FloatFilterRecursive3',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
        'not': Union[float, 'FloatFilterRecursive4'],
    },
    total=False,
)


FloatFilterRecursive4 = TypedDict(
    'FloatFilterRecursive4',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
            },
    total=False,
)


class FloatWithAggregatesFilter(FloatFilter, total=False):
    _max: 'FloatFilter'
    _min: 'FloatFilter'
    _sum: 'FloatFilter'
    _avg: 'FloatFilter'
    _count: 'IntFilter'


    

BytesFilter = TypedDict(
    'BytesFilter',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
        'not': Union['fields.Base64', 'BytesFilterRecursive1'],
    },
    total=False,
)


BytesFilterRecursive1 = TypedDict(
    'BytesFilterRecursive1',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
        'not': Union['fields.Base64', 'BytesFilterRecursive2'],
    },
    total=False,
)


BytesFilterRecursive2 = TypedDict(
    'BytesFilterRecursive2',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
        'not': Union['fields.Base64', 'BytesFilterRecursive3'],
    },
    total=False,
)


BytesFilterRecursive3 = TypedDict(
    'BytesFilterRecursive3',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
        'not': Union['fields.Base64', 'BytesFilterRecursive4'],
    },
    total=False,
)


BytesFilterRecursive4 = TypedDict(
    'BytesFilterRecursive4',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
            },
    total=False,
)


class BytesWithAggregatesFilter(BytesFilter, total=False):
    _max: 'BytesFilter'
    _min: 'BytesFilter'
    _sum: 'BytesFilter'
    _avg: 'BytesFilter'
    _count: 'IntFilter'


# TODO: preview feature for improving JSON filtering
JsonFilter = TypedDict(
    'JsonFilter',
    {
        'equals': 'fields.Json',
        'not': 'fields.Json',
    },
    total=False,
)


class JsonWithAggregatesFilter(JsonFilter, total=False):
    _max: 'JsonFilter'
    _min: 'JsonFilter'
    _sum: 'JsonFilter'
    _avg: 'JsonFilter'
    _count: 'IntFilter'


    

DecimalFilter = TypedDict(
    'DecimalFilter',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
        'not': Union[decimal.Decimal, 'DecimalFilterRecursive1'],
    },
    total=False,
)


DecimalFilterRecursive1 = TypedDict(
    'DecimalFilterRecursive1',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
        'not': Union[decimal.Decimal, 'DecimalFilterRecursive2'],
    },
    total=False,
)


DecimalFilterRecursive2 = TypedDict(
    'DecimalFilterRecursive2',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
        'not': Union[decimal.Decimal, 'DecimalFilterRecursive3'],
    },
    total=False,
)


DecimalFilterRecursive3 = TypedDict(
    'DecimalFilterRecursive3',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
        'not': Union[decimal.Decimal, 'DecimalFilterRecursive4'],
    },
    total=False,
)


DecimalFilterRecursive4 = TypedDict(
    'DecimalFilterRecursive4',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
            },
    total=False,
)


class DecimalWithAggregatesFilter(StringFilter, total=False):
    _max: 'DecimalFilter'
    _min: 'DecimalFilter'
    _sum: 'DecimalFilter'
    _avg: 'DecimalFilter'
    _count: 'IntFilter'


class _FloatSetInput(TypedDict):
    set: float


class _FloatDivideInput(TypedDict):
    divide: float


class _FloatMultiplyInput(TypedDict):
    multiply: float


class _FloatIncrementInput(TypedDict):
    increment: float


class _FloatDecrementInput(TypedDict):
    decrement: float


class _IntSetInput(TypedDict):
    set: int


class _IntDivideInput(TypedDict):
    divide: int


class _IntMultiplyInput(TypedDict):
    multiply: int


class _IntIncrementInput(TypedDict):
    increment: int


class _IntDecrementInput(TypedDict):
    decrement: int


AtomicFloatInput = Union[
    _FloatSetInput,
    _FloatDivideInput,
    _FloatMultiplyInput,
    _FloatIncrementInput,
    _FloatDecrementInput,
]
AtomicIntInput = Union[
    _IntSetInput,
    _IntDivideInput,
    _IntMultiplyInput,
    _IntIncrementInput,
    _IntDecrementInput,
]
AtomicBigIntInput = AtomicIntInput

class _StringListFilterEqualsInput(TypedDict):
    equals: Optional[List[_str]]


class _StringListFilterHasInput(TypedDict):
    has: _str


class _StringListFilterHasEveryInput(TypedDict):
    has_every: List[_str]


class _StringListFilterHasSomeInput(TypedDict):
    has_some: List[_str]


class _StringListFilterIsEmptyInput(TypedDict):
    is_empty: bool


StringListFilter = Union[
    _StringListFilterHasInput,
    _StringListFilterEqualsInput,
    _StringListFilterHasSomeInput,
    _StringListFilterIsEmptyInput,
    _StringListFilterHasEveryInput,
]


class _StringListUpdateSet(TypedDict):
    set: List[_str]


class _StringListUpdatePush(TypedDict):
    push: List[_str]


StringListUpdate = Union[
    List[_str],
    _StringListUpdateSet,
    _StringListUpdatePush,
]

class _BytesListFilterEqualsInput(TypedDict):
    equals: Optional[List['fields.Base64']]


class _BytesListFilterHasInput(TypedDict):
    has: 'fields.Base64'


class _BytesListFilterHasEveryInput(TypedDict):
    has_every: List['fields.Base64']


class _BytesListFilterHasSomeInput(TypedDict):
    has_some: List['fields.Base64']


class _BytesListFilterIsEmptyInput(TypedDict):
    is_empty: bool


BytesListFilter = Union[
    _BytesListFilterHasInput,
    _BytesListFilterEqualsInput,
    _BytesListFilterHasSomeInput,
    _BytesListFilterIsEmptyInput,
    _BytesListFilterHasEveryInput,
]


class _BytesListUpdateSet(TypedDict):
    set: List['fields.Base64']


class _BytesListUpdatePush(TypedDict):
    push: List['fields.Base64']


BytesListUpdate = Union[
    List['fields.Base64'],
    _BytesListUpdateSet,
    _BytesListUpdatePush,
]

class _DateTimeListFilterEqualsInput(TypedDict):
    equals: Optional[List[datetime.datetime]]


class _DateTimeListFilterHasInput(TypedDict):
    has: datetime.datetime


class _DateTimeListFilterHasEveryInput(TypedDict):
    has_every: List[datetime.datetime]


class _DateTimeListFilterHasSomeInput(TypedDict):
    has_some: List[datetime.datetime]


class _DateTimeListFilterIsEmptyInput(TypedDict):
    is_empty: bool


DateTimeListFilter = Union[
    _DateTimeListFilterHasInput,
    _DateTimeListFilterEqualsInput,
    _DateTimeListFilterHasSomeInput,
    _DateTimeListFilterIsEmptyInput,
    _DateTimeListFilterHasEveryInput,
]


class _DateTimeListUpdateSet(TypedDict):
    set: List[datetime.datetime]


class _DateTimeListUpdatePush(TypedDict):
    push: List[datetime.datetime]


DateTimeListUpdate = Union[
    List[datetime.datetime],
    _DateTimeListUpdateSet,
    _DateTimeListUpdatePush,
]

class _BooleanListFilterEqualsInput(TypedDict):
    equals: Optional[List[_bool]]


class _BooleanListFilterHasInput(TypedDict):
    has: _bool


class _BooleanListFilterHasEveryInput(TypedDict):
    has_every: List[_bool]


class _BooleanListFilterHasSomeInput(TypedDict):
    has_some: List[_bool]


class _BooleanListFilterIsEmptyInput(TypedDict):
    is_empty: bool


BooleanListFilter = Union[
    _BooleanListFilterHasInput,
    _BooleanListFilterEqualsInput,
    _BooleanListFilterHasSomeInput,
    _BooleanListFilterIsEmptyInput,
    _BooleanListFilterHasEveryInput,
]


class _BooleanListUpdateSet(TypedDict):
    set: List[_bool]


class _BooleanListUpdatePush(TypedDict):
    push: List[_bool]


BooleanListUpdate = Union[
    List[_bool],
    _BooleanListUpdateSet,
    _BooleanListUpdatePush,
]

class _IntListFilterEqualsInput(TypedDict):
    equals: Optional[List[_int]]


class _IntListFilterHasInput(TypedDict):
    has: _int


class _IntListFilterHasEveryInput(TypedDict):
    has_every: List[_int]


class _IntListFilterHasSomeInput(TypedDict):
    has_some: List[_int]


class _IntListFilterIsEmptyInput(TypedDict):
    is_empty: bool


IntListFilter = Union[
    _IntListFilterHasInput,
    _IntListFilterEqualsInput,
    _IntListFilterHasSomeInput,
    _IntListFilterIsEmptyInput,
    _IntListFilterHasEveryInput,
]


class _IntListUpdateSet(TypedDict):
    set: List[_int]


class _IntListUpdatePush(TypedDict):
    push: List[_int]


IntListUpdate = Union[
    List[_int],
    _IntListUpdateSet,
    _IntListUpdatePush,
]

class _BigIntListFilterEqualsInput(TypedDict):
    equals: Optional[List[_int]]


class _BigIntListFilterHasInput(TypedDict):
    has: _int


class _BigIntListFilterHasEveryInput(TypedDict):
    has_every: List[_int]


class _BigIntListFilterHasSomeInput(TypedDict):
    has_some: List[_int]


class _BigIntListFilterIsEmptyInput(TypedDict):
    is_empty: bool


BigIntListFilter = Union[
    _BigIntListFilterHasInput,
    _BigIntListFilterEqualsInput,
    _BigIntListFilterHasSomeInput,
    _BigIntListFilterIsEmptyInput,
    _BigIntListFilterHasEveryInput,
]


class _BigIntListUpdateSet(TypedDict):
    set: List[_int]


class _BigIntListUpdatePush(TypedDict):
    push: List[_int]


BigIntListUpdate = Union[
    List[_int],
    _BigIntListUpdateSet,
    _BigIntListUpdatePush,
]

class _FloatListFilterEqualsInput(TypedDict):
    equals: Optional[List[_float]]


class _FloatListFilterHasInput(TypedDict):
    has: _float


class _FloatListFilterHasEveryInput(TypedDict):
    has_every: List[_float]


class _FloatListFilterHasSomeInput(TypedDict):
    has_some: List[_float]


class _FloatListFilterIsEmptyInput(TypedDict):
    is_empty: bool


FloatListFilter = Union[
    _FloatListFilterHasInput,
    _FloatListFilterEqualsInput,
    _FloatListFilterHasSomeInput,
    _FloatListFilterIsEmptyInput,
    _FloatListFilterHasEveryInput,
]


class _FloatListUpdateSet(TypedDict):
    set: List[_float]


class _FloatListUpdatePush(TypedDict):
    push: List[_float]


FloatListUpdate = Union[
    List[_float],
    _FloatListUpdateSet,
    _FloatListUpdatePush,
]

class _JsonListFilterEqualsInput(TypedDict):
    equals: Optional[List['fields.Json']]


class _JsonListFilterHasInput(TypedDict):
    has: 'fields.Json'


class _JsonListFilterHasEveryInput(TypedDict):
    has_every: List['fields.Json']


class _JsonListFilterHasSomeInput(TypedDict):
    has_some: List['fields.Json']


class _JsonListFilterIsEmptyInput(TypedDict):
    is_empty: bool


JsonListFilter = Union[
    _JsonListFilterHasInput,
    _JsonListFilterEqualsInput,
    _JsonListFilterHasSomeInput,
    _JsonListFilterIsEmptyInput,
    _JsonListFilterHasEveryInput,
]


class _JsonListUpdateSet(TypedDict):
    set: List['fields.Json']


class _JsonListUpdatePush(TypedDict):
    push: List['fields.Json']


JsonListUpdate = Union[
    List['fields.Json'],
    _JsonListUpdateSet,
    _JsonListUpdatePush,
]

class _DecimalListFilterEqualsInput(TypedDict):
    equals: Optional[List[decimal.Decimal]]


class _DecimalListFilterHasInput(TypedDict):
    has: decimal.Decimal


class _DecimalListFilterHasEveryInput(TypedDict):
    has_every: List[decimal.Decimal]


class _DecimalListFilterHasSomeInput(TypedDict):
    has_some: List[decimal.Decimal]


class _DecimalListFilterIsEmptyInput(TypedDict):
    is_empty: bool


DecimalListFilter = Union[
    _DecimalListFilterHasInput,
    _DecimalListFilterEqualsInput,
    _DecimalListFilterHasSomeInput,
    _DecimalListFilterIsEmptyInput,
    _DecimalListFilterHasEveryInput,
]


class _DecimalListUpdateSet(TypedDict):
    set: List[decimal.Decimal]


class _DecimalListUpdatePush(TypedDict):
    push: List[decimal.Decimal]


DecimalListUpdate = Union[
    List[decimal.Decimal],
    _DecimalListUpdateSet,
    _DecimalListUpdatePush,
]


# ScrapeJob types

class ScrapeJobOptionalCreateInput(TypedDict, total=False):
    """Optional arguments to the ScrapeJob create method"""
    id: _str
    status: _str
    apifyRunId: Optional[_str]
    result: Optional['fields.Json']
    error: Optional[_str]
    createdAt: datetime.datetime
    updatedAt: datetime.datetime


class ScrapeJobCreateInput(ScrapeJobOptionalCreateInput):
    """Required arguments to the ScrapeJob create method"""
    linkedinUrls: 'fields.Json'
    maxPosts: _int


# TODO: remove this in favour of without explicit relations
# e.g. PostCreateWithoutAuthorInput

class ScrapeJobOptionalCreateWithoutRelationsInput(TypedDict, total=False):
    """Optional arguments to the ScrapeJob create method, without relations"""
    id: _str
    status: _str
    apifyRunId: Optional[_str]
    result: Optional['fields.Json']
    error: Optional[_str]
    createdAt: datetime.datetime
    updatedAt: datetime.datetime


class ScrapeJobCreateWithoutRelationsInput(ScrapeJobOptionalCreateWithoutRelationsInput):
    """Required arguments to the ScrapeJob create method, without relations"""
    linkedinUrls: 'fields.Json'
    maxPosts: _int


class ScrapeJobCreateNestedWithoutRelationsInput(TypedDict, total=False):
    create: 'ScrapeJobCreateWithoutRelationsInput'
    connect: 'ScrapeJobWhereUniqueInput'


class ScrapeJobCreateManyNestedWithoutRelationsInput(TypedDict, total=False):
    create: Union['ScrapeJobCreateWithoutRelationsInput', List['ScrapeJobCreateWithoutRelationsInput']]
    connect: Union['ScrapeJobWhereUniqueInput', List['ScrapeJobWhereUniqueInput']]


_ScrapeJobWhereUnique_id_Input = TypedDict(
    '_ScrapeJobWhereUnique_id_Input',
    {
        'id': '_str',
    },
    total=True
)

ScrapeJobWhereUniqueInput = _ScrapeJobWhereUnique_id_Input


class ScrapeJobUpdateInput(TypedDict, total=False):
    """Optional arguments for updating a record"""
    id: _str
    status: _str
    linkedinUrls: 'fields.Json'
    maxPosts: Union[AtomicIntInput, _int]
    apifyRunId: Optional[_str]
    result: Optional['fields.Json']
    error: Optional[_str]
    createdAt: datetime.datetime
    updatedAt: datetime.datetime


class ScrapeJobUpdateManyMutationInput(TypedDict, total=False):
    """Arguments for updating many records"""
    id: _str
    status: _str
    linkedinUrls: 'fields.Json'
    maxPosts: Union[AtomicIntInput, _int]
    apifyRunId: Optional[_str]
    result: Optional['fields.Json']
    error: Optional[_str]
    createdAt: datetime.datetime
    updatedAt: datetime.datetime


class ScrapeJobUpdateManyWithoutRelationsInput(TypedDict, total=False):
    create: List['ScrapeJobCreateWithoutRelationsInput']
    connect: List['ScrapeJobWhereUniqueInput']
    set: List['ScrapeJobWhereUniqueInput']
    disconnect: List['ScrapeJobWhereUniqueInput']
    delete: List['ScrapeJobWhereUniqueInput']

    # TODO
    # update: List['ScrapeJobUpdateWithWhereUniqueWithoutRelationsInput']
    # updateMany: List['ScrapeJobUpdateManyWithWhereUniqueWithoutRelationsInput']
    # deleteMany: List['ScrapeJobScalarWhereInput']
    # upsert: List['ScrapeJobUpserteWithWhereUniqueWithoutRelationsInput']
    # connectOrCreate: List['ScrapeJobCreateOrConnectWithoutRelationsInput']


class ScrapeJobUpdateOneWithoutRelationsInput(TypedDict, total=False):
    create: 'ScrapeJobCreateWithoutRelationsInput'
    connect: 'ScrapeJobWhereUniqueInput'
    disconnect: bool
    delete: bool

    # TODO
    # update: 'ScrapeJobUpdateInput'
    # upsert: 'ScrapeJobUpsertWithoutRelationsInput'
    # connectOrCreate: 'ScrapeJobCreateOrConnectWithoutRelationsInput'


class ScrapeJobUpsertInput(TypedDict):
    create: 'ScrapeJobCreateInput'
    update: 'ScrapeJobUpdateInput'  # pyright: ignore[reportIncompatibleMethodOverride]


_ScrapeJob_id_OrderByInput = TypedDict(
    '_ScrapeJob_id_OrderByInput',
    {
        'id': 'SortOrder',
    },
    total=True
)

_ScrapeJob_status_OrderByInput = TypedDict(
    '_ScrapeJob_status_OrderByInput',
    {
        'status': 'SortOrder',
    },
    total=True
)

_ScrapeJob_linkedinUrls_OrderByInput = TypedDict(
    '_ScrapeJob_linkedinUrls_OrderByInput',
    {
        'linkedinUrls': 'SortOrder',
    },
    total=True
)

_ScrapeJob_maxPosts_OrderByInput = TypedDict(
    '_ScrapeJob_maxPosts_OrderByInput',
    {
        'maxPosts': 'SortOrder',
    },
    total=True
)

_ScrapeJob_apifyRunId_OrderByInput = TypedDict(
    '_ScrapeJob_apifyRunId_OrderByInput',
    {
        'apifyRunId': 'SortOrder',
    },
    total=True
)

_ScrapeJob_result_OrderByInput = TypedDict(
    '_ScrapeJob_result_OrderByInput',
    {
        'result': 'SortOrder',
    },
    total=True
)

_ScrapeJob_error_OrderByInput = TypedDict(
    '_ScrapeJob_error_OrderByInput',
    {
        'error': 'SortOrder',
    },
    total=True
)

_ScrapeJob_createdAt_OrderByInput = TypedDict(
    '_ScrapeJob_createdAt_OrderByInput',
    {
        'createdAt': 'SortOrder',
    },
    total=True
)

_ScrapeJob_updatedAt_OrderByInput = TypedDict(
    '_ScrapeJob_updatedAt_OrderByInput',
    {
        'updatedAt': 'SortOrder',
    },
    total=True
)

ScrapeJobOrderByInput = Union[
    '_ScrapeJob_id_OrderByInput',
    '_ScrapeJob_status_OrderByInput',
    '_ScrapeJob_linkedinUrls_OrderByInput',
    '_ScrapeJob_maxPosts_OrderByInput',
    '_ScrapeJob_apifyRunId_OrderByInput',
    '_ScrapeJob_result_OrderByInput',
    '_ScrapeJob_error_OrderByInput',
    '_ScrapeJob_createdAt_OrderByInput',
    '_ScrapeJob_updatedAt_OrderByInput',
]



# recursive ScrapeJob types
# TODO: cleanup these types


# Dict[str, Any] is a mypy limitation
# see https://github.com/RobertCraigie/prisma-client-py/issues/45
# switch to pyright for improved types, see https://prisma-client-py.readthedocs.io/en/stable/reference/limitations/

ScrapeJobRelationFilter = TypedDict(
    'ScrapeJobRelationFilter',
    {
        'is': 'Dict[str, Any]',
        'is_not': 'Dict[str, Any]',
    },
    total=False,
)


class ScrapeJobListRelationFilter(TypedDict, total=False):
    some: 'Dict[str, Any]'
    none: 'Dict[str, Any]'
    every: 'Dict[str, Any]'


class ScrapeJobInclude(TypedDict, total=False):
    """ScrapeJob relational arguments"""


    

class ScrapeJobIncludeFromScrapeJob(TypedDict, total=False):
    """Relational arguments for ScrapeJob"""


class ScrapeJobIncludeFromScrapeJobRecursive1(TypedDict, total=False):
    """Relational arguments for ScrapeJob"""


class ScrapeJobIncludeFromScrapeJobRecursive2(TypedDict, total=False):
    """Relational arguments for ScrapeJob"""


class ScrapeJobIncludeFromScrapeJobRecursive3(TypedDict, total=False):
    """Relational arguments for ScrapeJob"""


class ScrapeJobIncludeFromScrapeJobRecursive4(TypedDict, total=False):
    """Relational arguments for ScrapeJob"""

    

class ScrapeJobArgsFromScrapeJob(TypedDict, total=False):
    """Arguments for ScrapeJob"""
    include: 'ScrapeJobIncludeFromScrapeJobRecursive1'


class ScrapeJobArgsFromScrapeJobRecursive1(TypedDict, total=False):
    """Arguments for ScrapeJob"""
    include: 'ScrapeJobIncludeFromScrapeJobRecursive2'


class ScrapeJobArgsFromScrapeJobRecursive2(TypedDict, total=False):
    """Arguments for ScrapeJob"""
    include: 'ScrapeJobIncludeFromScrapeJobRecursive3'


class ScrapeJobArgsFromScrapeJobRecursive3(TypedDict, total=False):
    """Arguments for ScrapeJob"""
    include: 'ScrapeJobIncludeFromScrapeJobRecursive4'


class ScrapeJobArgsFromScrapeJobRecursive4(TypedDict, total=False):
    """Arguments for ScrapeJob"""
    
    

class FindManyScrapeJobArgsFromScrapeJob(TypedDict, total=False):
    """Arguments for ScrapeJob"""
    take: int
    skip: int
    order_by: Union['ScrapeJobOrderByInput', List['ScrapeJobOrderByInput']]
    where: 'ScrapeJobWhereInput'
    cursor: 'ScrapeJobWhereUniqueInput'
    distinct: List['ScrapeJobScalarFieldKeys']
    include: 'ScrapeJobIncludeFromScrapeJobRecursive1'


class FindManyScrapeJobArgsFromScrapeJobRecursive1(TypedDict, total=False):
    """Arguments for ScrapeJob"""
    take: int
    skip: int
    order_by: Union['ScrapeJobOrderByInput', List['ScrapeJobOrderByInput']]
    where: 'ScrapeJobWhereInput'
    cursor: 'ScrapeJobWhereUniqueInput'
    distinct: List['ScrapeJobScalarFieldKeys']
    include: 'ScrapeJobIncludeFromScrapeJobRecursive2'


class FindManyScrapeJobArgsFromScrapeJobRecursive2(TypedDict, total=False):
    """Arguments for ScrapeJob"""
    take: int
    skip: int
    order_by: Union['ScrapeJobOrderByInput', List['ScrapeJobOrderByInput']]
    where: 'ScrapeJobWhereInput'
    cursor: 'ScrapeJobWhereUniqueInput'
    distinct: List['ScrapeJobScalarFieldKeys']
    include: 'ScrapeJobIncludeFromScrapeJobRecursive3'


class FindManyScrapeJobArgsFromScrapeJobRecursive3(TypedDict, total=False):
    """Arguments for ScrapeJob"""
    take: int
    skip: int
    order_by: Union['ScrapeJobOrderByInput', List['ScrapeJobOrderByInput']]
    where: 'ScrapeJobWhereInput'
    cursor: 'ScrapeJobWhereUniqueInput'
    distinct: List['ScrapeJobScalarFieldKeys']
    include: 'ScrapeJobIncludeFromScrapeJobRecursive4'


class FindManyScrapeJobArgsFromScrapeJobRecursive4(TypedDict, total=False):
    """Arguments for ScrapeJob"""
    take: int
    skip: int
    order_by: Union['ScrapeJobOrderByInput', List['ScrapeJobOrderByInput']]
    where: 'ScrapeJobWhereInput'
    cursor: 'ScrapeJobWhereUniqueInput'
    distinct: List['ScrapeJobScalarFieldKeys']
    
    

class SearchQueryIncludeFromScrapeJob(TypedDict, total=False):
    """Relational arguments for ScrapeJob"""


class SearchQueryIncludeFromScrapeJobRecursive1(TypedDict, total=False):
    """Relational arguments for ScrapeJob"""


class SearchQueryIncludeFromScrapeJobRecursive2(TypedDict, total=False):
    """Relational arguments for ScrapeJob"""


class SearchQueryIncludeFromScrapeJobRecursive3(TypedDict, total=False):
    """Relational arguments for ScrapeJob"""


class SearchQueryIncludeFromScrapeJobRecursive4(TypedDict, total=False):
    """Relational arguments for ScrapeJob"""

    

class SearchQueryArgsFromScrapeJob(TypedDict, total=False):
    """Arguments for ScrapeJob"""
    include: 'SearchQueryIncludeFromSearchQueryRecursive1'


class SearchQueryArgsFromScrapeJobRecursive1(TypedDict, total=False):
    """Arguments for ScrapeJob"""
    include: 'SearchQueryIncludeFromSearchQueryRecursive2'


class SearchQueryArgsFromScrapeJobRecursive2(TypedDict, total=False):
    """Arguments for ScrapeJob"""
    include: 'SearchQueryIncludeFromSearchQueryRecursive3'


class SearchQueryArgsFromScrapeJobRecursive3(TypedDict, total=False):
    """Arguments for ScrapeJob"""
    include: 'SearchQueryIncludeFromSearchQueryRecursive4'


class SearchQueryArgsFromScrapeJobRecursive4(TypedDict, total=False):
    """Arguments for ScrapeJob"""
    
    

class FindManySearchQueryArgsFromScrapeJob(TypedDict, total=False):
    """Arguments for ScrapeJob"""
    take: int
    skip: int
    order_by: Union['SearchQueryOrderByInput', List['SearchQueryOrderByInput']]
    where: 'SearchQueryWhereInput'
    cursor: 'SearchQueryWhereUniqueInput'
    distinct: List['SearchQueryScalarFieldKeys']
    include: 'SearchQueryIncludeFromSearchQueryRecursive1'


class FindManySearchQueryArgsFromScrapeJobRecursive1(TypedDict, total=False):
    """Arguments for ScrapeJob"""
    take: int
    skip: int
    order_by: Union['SearchQueryOrderByInput', List['SearchQueryOrderByInput']]
    where: 'SearchQueryWhereInput'
    cursor: 'SearchQueryWhereUniqueInput'
    distinct: List['SearchQueryScalarFieldKeys']
    include: 'SearchQueryIncludeFromSearchQueryRecursive2'


class FindManySearchQueryArgsFromScrapeJobRecursive2(TypedDict, total=False):
    """Arguments for ScrapeJob"""
    take: int
    skip: int
    order_by: Union['SearchQueryOrderByInput', List['SearchQueryOrderByInput']]
    where: 'SearchQueryWhereInput'
    cursor: 'SearchQueryWhereUniqueInput'
    distinct: List['SearchQueryScalarFieldKeys']
    include: 'SearchQueryIncludeFromSearchQueryRecursive3'


class FindManySearchQueryArgsFromScrapeJobRecursive3(TypedDict, total=False):
    """Arguments for ScrapeJob"""
    take: int
    skip: int
    order_by: Union['SearchQueryOrderByInput', List['SearchQueryOrderByInput']]
    where: 'SearchQueryWhereInput'
    cursor: 'SearchQueryWhereUniqueInput'
    distinct: List['SearchQueryScalarFieldKeys']
    include: 'SearchQueryIncludeFromSearchQueryRecursive4'


class FindManySearchQueryArgsFromScrapeJobRecursive4(TypedDict, total=False):
    """Arguments for ScrapeJob"""
    take: int
    skip: int
    order_by: Union['SearchQueryOrderByInput', List['SearchQueryOrderByInput']]
    where: 'SearchQueryWhereInput'
    cursor: 'SearchQueryWhereUniqueInput'
    distinct: List['SearchQueryScalarFieldKeys']
    


FindManyScrapeJobArgs = FindManyScrapeJobArgsFromScrapeJob
FindFirstScrapeJobArgs = FindManyScrapeJobArgsFromScrapeJob


    

class ScrapeJobWhereInput(TypedDict, total=False):
    """ScrapeJob arguments for searching"""
    id: Union[_str, 'types.StringFilter']
    status: Union[_str, 'types.StringFilter']
    linkedinUrls: Union['fields.Json', 'types.JsonFilter']
    maxPosts: Union[_int, 'types.IntFilter']
    apifyRunId: Union[None, _str, 'types.StringFilter']
    result: Union[None, 'fields.Json', 'types.JsonFilter']
    error: Union[None, _str, 'types.StringFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeFilter']

    # should be noted that AND and NOT should be Union['ScrapeJobWhereInputRecursive1', List['ScrapeJobWhereInputRecursive1']]
    # but this causes mypy to hang :/
    AND: List['ScrapeJobWhereInputRecursive1']
    OR: List['ScrapeJobWhereInputRecursive1']
    NOT: List['ScrapeJobWhereInputRecursive1']


class ScrapeJobWhereInputRecursive1(TypedDict, total=False):
    """ScrapeJob arguments for searching"""
    id: Union[_str, 'types.StringFilter']
    status: Union[_str, 'types.StringFilter']
    linkedinUrls: Union['fields.Json', 'types.JsonFilter']
    maxPosts: Union[_int, 'types.IntFilter']
    apifyRunId: Union[None, _str, 'types.StringFilter']
    result: Union[None, 'fields.Json', 'types.JsonFilter']
    error: Union[None, _str, 'types.StringFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeFilter']

    # should be noted that AND and NOT should be Union['ScrapeJobWhereInputRecursive2', List['ScrapeJobWhereInputRecursive2']]
    # but this causes mypy to hang :/
    AND: List['ScrapeJobWhereInputRecursive2']
    OR: List['ScrapeJobWhereInputRecursive2']
    NOT: List['ScrapeJobWhereInputRecursive2']


class ScrapeJobWhereInputRecursive2(TypedDict, total=False):
    """ScrapeJob arguments for searching"""
    id: Union[_str, 'types.StringFilter']
    status: Union[_str, 'types.StringFilter']
    linkedinUrls: Union['fields.Json', 'types.JsonFilter']
    maxPosts: Union[_int, 'types.IntFilter']
    apifyRunId: Union[None, _str, 'types.StringFilter']
    result: Union[None, 'fields.Json', 'types.JsonFilter']
    error: Union[None, _str, 'types.StringFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeFilter']

    # should be noted that AND and NOT should be Union['ScrapeJobWhereInputRecursive3', List['ScrapeJobWhereInputRecursive3']]
    # but this causes mypy to hang :/
    AND: List['ScrapeJobWhereInputRecursive3']
    OR: List['ScrapeJobWhereInputRecursive3']
    NOT: List['ScrapeJobWhereInputRecursive3']


class ScrapeJobWhereInputRecursive3(TypedDict, total=False):
    """ScrapeJob arguments for searching"""
    id: Union[_str, 'types.StringFilter']
    status: Union[_str, 'types.StringFilter']
    linkedinUrls: Union['fields.Json', 'types.JsonFilter']
    maxPosts: Union[_int, 'types.IntFilter']
    apifyRunId: Union[None, _str, 'types.StringFilter']
    result: Union[None, 'fields.Json', 'types.JsonFilter']
    error: Union[None, _str, 'types.StringFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeFilter']

    # should be noted that AND and NOT should be Union['ScrapeJobWhereInputRecursive4', List['ScrapeJobWhereInputRecursive4']]
    # but this causes mypy to hang :/
    AND: List['ScrapeJobWhereInputRecursive4']
    OR: List['ScrapeJobWhereInputRecursive4']
    NOT: List['ScrapeJobWhereInputRecursive4']


class ScrapeJobWhereInputRecursive4(TypedDict, total=False):
    """ScrapeJob arguments for searching"""
    id: Union[_str, 'types.StringFilter']
    status: Union[_str, 'types.StringFilter']
    linkedinUrls: Union['fields.Json', 'types.JsonFilter']
    maxPosts: Union[_int, 'types.IntFilter']
    apifyRunId: Union[None, _str, 'types.StringFilter']
    result: Union[None, 'fields.Json', 'types.JsonFilter']
    error: Union[None, _str, 'types.StringFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeFilter']



# aggregate ScrapeJob types


    

class ScrapeJobScalarWhereWithAggregatesInput(TypedDict, total=False):
    """ScrapeJob arguments for searching"""
    id: Union[_str, 'types.StringWithAggregatesFilter']
    status: Union[_str, 'types.StringWithAggregatesFilter']
    linkedinUrls: Union['fields.Json', 'types.JsonWithAggregatesFilter']
    maxPosts: Union[_int, 'types.IntWithAggregatesFilter']
    apifyRunId: Union[_str, 'types.StringWithAggregatesFilter']
    result: Union['fields.Json', 'types.JsonWithAggregatesFilter']
    error: Union[_str, 'types.StringWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']

    AND: List['ScrapeJobScalarWhereWithAggregatesInputRecursive1']
    OR: List['ScrapeJobScalarWhereWithAggregatesInputRecursive1']
    NOT: List['ScrapeJobScalarWhereWithAggregatesInputRecursive1']


class ScrapeJobScalarWhereWithAggregatesInputRecursive1(TypedDict, total=False):
    """ScrapeJob arguments for searching"""
    id: Union[_str, 'types.StringWithAggregatesFilter']
    status: Union[_str, 'types.StringWithAggregatesFilter']
    linkedinUrls: Union['fields.Json', 'types.JsonWithAggregatesFilter']
    maxPosts: Union[_int, 'types.IntWithAggregatesFilter']
    apifyRunId: Union[_str, 'types.StringWithAggregatesFilter']
    result: Union['fields.Json', 'types.JsonWithAggregatesFilter']
    error: Union[_str, 'types.StringWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']

    AND: List['ScrapeJobScalarWhereWithAggregatesInputRecursive2']
    OR: List['ScrapeJobScalarWhereWithAggregatesInputRecursive2']
    NOT: List['ScrapeJobScalarWhereWithAggregatesInputRecursive2']


class ScrapeJobScalarWhereWithAggregatesInputRecursive2(TypedDict, total=False):
    """ScrapeJob arguments for searching"""
    id: Union[_str, 'types.StringWithAggregatesFilter']
    status: Union[_str, 'types.StringWithAggregatesFilter']
    linkedinUrls: Union['fields.Json', 'types.JsonWithAggregatesFilter']
    maxPosts: Union[_int, 'types.IntWithAggregatesFilter']
    apifyRunId: Union[_str, 'types.StringWithAggregatesFilter']
    result: Union['fields.Json', 'types.JsonWithAggregatesFilter']
    error: Union[_str, 'types.StringWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']

    AND: List['ScrapeJobScalarWhereWithAggregatesInputRecursive3']
    OR: List['ScrapeJobScalarWhereWithAggregatesInputRecursive3']
    NOT: List['ScrapeJobScalarWhereWithAggregatesInputRecursive3']


class ScrapeJobScalarWhereWithAggregatesInputRecursive3(TypedDict, total=False):
    """ScrapeJob arguments for searching"""
    id: Union[_str, 'types.StringWithAggregatesFilter']
    status: Union[_str, 'types.StringWithAggregatesFilter']
    linkedinUrls: Union['fields.Json', 'types.JsonWithAggregatesFilter']
    maxPosts: Union[_int, 'types.IntWithAggregatesFilter']
    apifyRunId: Union[_str, 'types.StringWithAggregatesFilter']
    result: Union['fields.Json', 'types.JsonWithAggregatesFilter']
    error: Union[_str, 'types.StringWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']

    AND: List['ScrapeJobScalarWhereWithAggregatesInputRecursive4']
    OR: List['ScrapeJobScalarWhereWithAggregatesInputRecursive4']
    NOT: List['ScrapeJobScalarWhereWithAggregatesInputRecursive4']


class ScrapeJobScalarWhereWithAggregatesInputRecursive4(TypedDict, total=False):
    """ScrapeJob arguments for searching"""
    id: Union[_str, 'types.StringWithAggregatesFilter']
    status: Union[_str, 'types.StringWithAggregatesFilter']
    linkedinUrls: Union['fields.Json', 'types.JsonWithAggregatesFilter']
    maxPosts: Union[_int, 'types.IntWithAggregatesFilter']
    apifyRunId: Union[_str, 'types.StringWithAggregatesFilter']
    result: Union['fields.Json', 'types.JsonWithAggregatesFilter']
    error: Union[_str, 'types.StringWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']



class ScrapeJobGroupByOutput(TypedDict, total=False):
    id: _str
    status: _str
    linkedinUrls: 'fields.Json'
    maxPosts: _int
    apifyRunId: _str
    result: 'fields.Json'
    error: _str
    createdAt: datetime.datetime
    updatedAt: datetime.datetime
    _sum: 'ScrapeJobSumAggregateOutput'
    _avg: 'ScrapeJobAvgAggregateOutput'
    _min: 'ScrapeJobMinAggregateOutput'
    _max: 'ScrapeJobMaxAggregateOutput'
    _count: 'ScrapeJobCountAggregateOutput'


class ScrapeJobAvgAggregateOutput(TypedDict, total=False):
    """ScrapeJob output for aggregating averages"""
    maxPosts: float


class ScrapeJobSumAggregateOutput(TypedDict, total=False):
    """ScrapeJob output for aggregating sums"""
    maxPosts: _int


class ScrapeJobScalarAggregateOutput(TypedDict, total=False):
    """ScrapeJob output including scalar fields"""
    id: _str
    status: _str
    linkedinUrls: 'fields.Json'
    maxPosts: _int
    apifyRunId: _str
    result: 'fields.Json'
    error: _str
    createdAt: datetime.datetime
    updatedAt: datetime.datetime


ScrapeJobMinAggregateOutput = ScrapeJobScalarAggregateOutput
ScrapeJobMaxAggregateOutput = ScrapeJobScalarAggregateOutput


class ScrapeJobMaxAggregateInput(TypedDict, total=False):
    """ScrapeJob input for aggregating by max"""
    id: bool
    status: bool
    linkedinUrls: bool
    maxPosts: bool
    apifyRunId: bool
    result: bool
    error: bool
    createdAt: bool
    updatedAt: bool


class ScrapeJobMinAggregateInput(TypedDict, total=False):
    """ScrapeJob input for aggregating by min"""
    id: bool
    status: bool
    linkedinUrls: bool
    maxPosts: bool
    apifyRunId: bool
    result: bool
    error: bool
    createdAt: bool
    updatedAt: bool


class ScrapeJobNumberAggregateInput(TypedDict, total=False):
    """ScrapeJob input for aggregating numbers"""
    maxPosts: bool


ScrapeJobAvgAggregateInput = ScrapeJobNumberAggregateInput
ScrapeJobSumAggregateInput = ScrapeJobNumberAggregateInput


ScrapeJobCountAggregateInput = TypedDict(
    'ScrapeJobCountAggregateInput',
    {
        'id': bool,
        'status': bool,
        'linkedinUrls': bool,
        'maxPosts': bool,
        'apifyRunId': bool,
        'result': bool,
        'error': bool,
        'createdAt': bool,
        'updatedAt': bool,
        '_all': bool,
    },
    total=False,
)

ScrapeJobCountAggregateOutput = TypedDict(
    'ScrapeJobCountAggregateOutput',
    {
        'id': int,
        'status': int,
        'linkedinUrls': int,
        'maxPosts': int,
        'apifyRunId': int,
        'result': int,
        'error': int,
        'createdAt': int,
        'updatedAt': int,
        '_all': int,
    },
    total=False,
)


ScrapeJobKeys = Literal[
    'id',
    'status',
    'linkedinUrls',
    'maxPosts',
    'apifyRunId',
    'result',
    'error',
    'createdAt',
    'updatedAt',
]
ScrapeJobScalarFieldKeys = Literal[
    'id',
    'status',
    'linkedinUrls',
    'maxPosts',
    'apifyRunId',
    'result',
    'error',
    'createdAt',
    'updatedAt',
]
ScrapeJobScalarFieldKeysT = TypeVar('ScrapeJobScalarFieldKeysT', bound=ScrapeJobScalarFieldKeys)

ScrapeJobRelationalFieldKeys = _NoneType

# SearchQuery types

class SearchQueryOptionalCreateInput(TypedDict, total=False):
    """Optional arguments to the SearchQuery create method"""
    id: _str
    createdAt: datetime.datetime


class SearchQueryCreateInput(SearchQueryOptionalCreateInput):
    """Required arguments to the SearchQuery create method"""
    filters: 'fields.Json'
    sqlQuery: _str
    resultCount: _int


# TODO: remove this in favour of without explicit relations
# e.g. PostCreateWithoutAuthorInput

class SearchQueryOptionalCreateWithoutRelationsInput(TypedDict, total=False):
    """Optional arguments to the SearchQuery create method, without relations"""
    id: _str
    createdAt: datetime.datetime


class SearchQueryCreateWithoutRelationsInput(SearchQueryOptionalCreateWithoutRelationsInput):
    """Required arguments to the SearchQuery create method, without relations"""
    filters: 'fields.Json'
    sqlQuery: _str
    resultCount: _int


class SearchQueryCreateNestedWithoutRelationsInput(TypedDict, total=False):
    create: 'SearchQueryCreateWithoutRelationsInput'
    connect: 'SearchQueryWhereUniqueInput'


class SearchQueryCreateManyNestedWithoutRelationsInput(TypedDict, total=False):
    create: Union['SearchQueryCreateWithoutRelationsInput', List['SearchQueryCreateWithoutRelationsInput']]
    connect: Union['SearchQueryWhereUniqueInput', List['SearchQueryWhereUniqueInput']]


_SearchQueryWhereUnique_id_Input = TypedDict(
    '_SearchQueryWhereUnique_id_Input',
    {
        'id': '_str',
    },
    total=True
)

SearchQueryWhereUniqueInput = _SearchQueryWhereUnique_id_Input


class SearchQueryUpdateInput(TypedDict, total=False):
    """Optional arguments for updating a record"""
    id: _str
    filters: 'fields.Json'
    sqlQuery: _str
    resultCount: Union[AtomicIntInput, _int]
    createdAt: datetime.datetime


class SearchQueryUpdateManyMutationInput(TypedDict, total=False):
    """Arguments for updating many records"""
    id: _str
    filters: 'fields.Json'
    sqlQuery: _str
    resultCount: Union[AtomicIntInput, _int]
    createdAt: datetime.datetime


class SearchQueryUpdateManyWithoutRelationsInput(TypedDict, total=False):
    create: List['SearchQueryCreateWithoutRelationsInput']
    connect: List['SearchQueryWhereUniqueInput']
    set: List['SearchQueryWhereUniqueInput']
    disconnect: List['SearchQueryWhereUniqueInput']
    delete: List['SearchQueryWhereUniqueInput']

    # TODO
    # update: List['SearchQueryUpdateWithWhereUniqueWithoutRelationsInput']
    # updateMany: List['SearchQueryUpdateManyWithWhereUniqueWithoutRelationsInput']
    # deleteMany: List['SearchQueryScalarWhereInput']
    # upsert: List['SearchQueryUpserteWithWhereUniqueWithoutRelationsInput']
    # connectOrCreate: List['SearchQueryCreateOrConnectWithoutRelationsInput']


class SearchQueryUpdateOneWithoutRelationsInput(TypedDict, total=False):
    create: 'SearchQueryCreateWithoutRelationsInput'
    connect: 'SearchQueryWhereUniqueInput'
    disconnect: bool
    delete: bool

    # TODO
    # update: 'SearchQueryUpdateInput'
    # upsert: 'SearchQueryUpsertWithoutRelationsInput'
    # connectOrCreate: 'SearchQueryCreateOrConnectWithoutRelationsInput'


class SearchQueryUpsertInput(TypedDict):
    create: 'SearchQueryCreateInput'
    update: 'SearchQueryUpdateInput'  # pyright: ignore[reportIncompatibleMethodOverride]


_SearchQuery_id_OrderByInput = TypedDict(
    '_SearchQuery_id_OrderByInput',
    {
        'id': 'SortOrder',
    },
    total=True
)

_SearchQuery_filters_OrderByInput = TypedDict(
    '_SearchQuery_filters_OrderByInput',
    {
        'filters': 'SortOrder',
    },
    total=True
)

_SearchQuery_sqlQuery_OrderByInput = TypedDict(
    '_SearchQuery_sqlQuery_OrderByInput',
    {
        'sqlQuery': 'SortOrder',
    },
    total=True
)

_SearchQuery_resultCount_OrderByInput = TypedDict(
    '_SearchQuery_resultCount_OrderByInput',
    {
        'resultCount': 'SortOrder',
    },
    total=True
)

_SearchQuery_createdAt_OrderByInput = TypedDict(
    '_SearchQuery_createdAt_OrderByInput',
    {
        'createdAt': 'SortOrder',
    },
    total=True
)

SearchQueryOrderByInput = Union[
    '_SearchQuery_id_OrderByInput',
    '_SearchQuery_filters_OrderByInput',
    '_SearchQuery_sqlQuery_OrderByInput',
    '_SearchQuery_resultCount_OrderByInput',
    '_SearchQuery_createdAt_OrderByInput',
]



# recursive SearchQuery types
# TODO: cleanup these types


# Dict[str, Any] is a mypy limitation
# see https://github.com/RobertCraigie/prisma-client-py/issues/45
# switch to pyright for improved types, see https://prisma-client-py.readthedocs.io/en/stable/reference/limitations/

SearchQueryRelationFilter = TypedDict(
    'SearchQueryRelationFilter',
    {
        'is': 'Dict[str, Any]',
        'is_not': 'Dict[str, Any]',
    },
    total=False,
)


class SearchQueryListRelationFilter(TypedDict, total=False):
    some: 'Dict[str, Any]'
    none: 'Dict[str, Any]'
    every: 'Dict[str, Any]'


class SearchQueryInclude(TypedDict, total=False):
    """SearchQuery relational arguments"""


    

class ScrapeJobIncludeFromSearchQuery(TypedDict, total=False):
    """Relational arguments for SearchQuery"""


class ScrapeJobIncludeFromSearchQueryRecursive1(TypedDict, total=False):
    """Relational arguments for SearchQuery"""


class ScrapeJobIncludeFromSearchQueryRecursive2(TypedDict, total=False):
    """Relational arguments for SearchQuery"""


class ScrapeJobIncludeFromSearchQueryRecursive3(TypedDict, total=False):
    """Relational arguments for SearchQuery"""


class ScrapeJobIncludeFromSearchQueryRecursive4(TypedDict, total=False):
    """Relational arguments for SearchQuery"""

    

class ScrapeJobArgsFromSearchQuery(TypedDict, total=False):
    """Arguments for SearchQuery"""
    include: 'ScrapeJobIncludeFromScrapeJobRecursive1'


class ScrapeJobArgsFromSearchQueryRecursive1(TypedDict, total=False):
    """Arguments for SearchQuery"""
    include: 'ScrapeJobIncludeFromScrapeJobRecursive2'


class ScrapeJobArgsFromSearchQueryRecursive2(TypedDict, total=False):
    """Arguments for SearchQuery"""
    include: 'ScrapeJobIncludeFromScrapeJobRecursive3'


class ScrapeJobArgsFromSearchQueryRecursive3(TypedDict, total=False):
    """Arguments for SearchQuery"""
    include: 'ScrapeJobIncludeFromScrapeJobRecursive4'


class ScrapeJobArgsFromSearchQueryRecursive4(TypedDict, total=False):
    """Arguments for SearchQuery"""
    
    

class FindManyScrapeJobArgsFromSearchQuery(TypedDict, total=False):
    """Arguments for SearchQuery"""
    take: int
    skip: int
    order_by: Union['ScrapeJobOrderByInput', List['ScrapeJobOrderByInput']]
    where: 'ScrapeJobWhereInput'
    cursor: 'ScrapeJobWhereUniqueInput'
    distinct: List['ScrapeJobScalarFieldKeys']
    include: 'ScrapeJobIncludeFromScrapeJobRecursive1'


class FindManyScrapeJobArgsFromSearchQueryRecursive1(TypedDict, total=False):
    """Arguments for SearchQuery"""
    take: int
    skip: int
    order_by: Union['ScrapeJobOrderByInput', List['ScrapeJobOrderByInput']]
    where: 'ScrapeJobWhereInput'
    cursor: 'ScrapeJobWhereUniqueInput'
    distinct: List['ScrapeJobScalarFieldKeys']
    include: 'ScrapeJobIncludeFromScrapeJobRecursive2'


class FindManyScrapeJobArgsFromSearchQueryRecursive2(TypedDict, total=False):
    """Arguments for SearchQuery"""
    take: int
    skip: int
    order_by: Union['ScrapeJobOrderByInput', List['ScrapeJobOrderByInput']]
    where: 'ScrapeJobWhereInput'
    cursor: 'ScrapeJobWhereUniqueInput'
    distinct: List['ScrapeJobScalarFieldKeys']
    include: 'ScrapeJobIncludeFromScrapeJobRecursive3'


class FindManyScrapeJobArgsFromSearchQueryRecursive3(TypedDict, total=False):
    """Arguments for SearchQuery"""
    take: int
    skip: int
    order_by: Union['ScrapeJobOrderByInput', List['ScrapeJobOrderByInput']]
    where: 'ScrapeJobWhereInput'
    cursor: 'ScrapeJobWhereUniqueInput'
    distinct: List['ScrapeJobScalarFieldKeys']
    include: 'ScrapeJobIncludeFromScrapeJobRecursive4'


class FindManyScrapeJobArgsFromSearchQueryRecursive4(TypedDict, total=False):
    """Arguments for SearchQuery"""
    take: int
    skip: int
    order_by: Union['ScrapeJobOrderByInput', List['ScrapeJobOrderByInput']]
    where: 'ScrapeJobWhereInput'
    cursor: 'ScrapeJobWhereUniqueInput'
    distinct: List['ScrapeJobScalarFieldKeys']
    
    

class SearchQueryIncludeFromSearchQuery(TypedDict, total=False):
    """Relational arguments for SearchQuery"""


class SearchQueryIncludeFromSearchQueryRecursive1(TypedDict, total=False):
    """Relational arguments for SearchQuery"""


class SearchQueryIncludeFromSearchQueryRecursive2(TypedDict, total=False):
    """Relational arguments for SearchQuery"""


class SearchQueryIncludeFromSearchQueryRecursive3(TypedDict, total=False):
    """Relational arguments for SearchQuery"""


class SearchQueryIncludeFromSearchQueryRecursive4(TypedDict, total=False):
    """Relational arguments for SearchQuery"""

    

class SearchQueryArgsFromSearchQuery(TypedDict, total=False):
    """Arguments for SearchQuery"""
    include: 'SearchQueryIncludeFromSearchQueryRecursive1'


class SearchQueryArgsFromSearchQueryRecursive1(TypedDict, total=False):
    """Arguments for SearchQuery"""
    include: 'SearchQueryIncludeFromSearchQueryRecursive2'


class SearchQueryArgsFromSearchQueryRecursive2(TypedDict, total=False):
    """Arguments for SearchQuery"""
    include: 'SearchQueryIncludeFromSearchQueryRecursive3'


class SearchQueryArgsFromSearchQueryRecursive3(TypedDict, total=False):
    """Arguments for SearchQuery"""
    include: 'SearchQueryIncludeFromSearchQueryRecursive4'


class SearchQueryArgsFromSearchQueryRecursive4(TypedDict, total=False):
    """Arguments for SearchQuery"""
    
    

class FindManySearchQueryArgsFromSearchQuery(TypedDict, total=False):
    """Arguments for SearchQuery"""
    take: int
    skip: int
    order_by: Union['SearchQueryOrderByInput', List['SearchQueryOrderByInput']]
    where: 'SearchQueryWhereInput'
    cursor: 'SearchQueryWhereUniqueInput'
    distinct: List['SearchQueryScalarFieldKeys']
    include: 'SearchQueryIncludeFromSearchQueryRecursive1'


class FindManySearchQueryArgsFromSearchQueryRecursive1(TypedDict, total=False):
    """Arguments for SearchQuery"""
    take: int
    skip: int
    order_by: Union['SearchQueryOrderByInput', List['SearchQueryOrderByInput']]
    where: 'SearchQueryWhereInput'
    cursor: 'SearchQueryWhereUniqueInput'
    distinct: List['SearchQueryScalarFieldKeys']
    include: 'SearchQueryIncludeFromSearchQueryRecursive2'


class FindManySearchQueryArgsFromSearchQueryRecursive2(TypedDict, total=False):
    """Arguments for SearchQuery"""
    take: int
    skip: int
    order_by: Union['SearchQueryOrderByInput', List['SearchQueryOrderByInput']]
    where: 'SearchQueryWhereInput'
    cursor: 'SearchQueryWhereUniqueInput'
    distinct: List['SearchQueryScalarFieldKeys']
    include: 'SearchQueryIncludeFromSearchQueryRecursive3'


class FindManySearchQueryArgsFromSearchQueryRecursive3(TypedDict, total=False):
    """Arguments for SearchQuery"""
    take: int
    skip: int
    order_by: Union['SearchQueryOrderByInput', List['SearchQueryOrderByInput']]
    where: 'SearchQueryWhereInput'
    cursor: 'SearchQueryWhereUniqueInput'
    distinct: List['SearchQueryScalarFieldKeys']
    include: 'SearchQueryIncludeFromSearchQueryRecursive4'


class FindManySearchQueryArgsFromSearchQueryRecursive4(TypedDict, total=False):
    """Arguments for SearchQuery"""
    take: int
    skip: int
    order_by: Union['SearchQueryOrderByInput', List['SearchQueryOrderByInput']]
    where: 'SearchQueryWhereInput'
    cursor: 'SearchQueryWhereUniqueInput'
    distinct: List['SearchQueryScalarFieldKeys']
    


FindManySearchQueryArgs = FindManySearchQueryArgsFromSearchQuery
FindFirstSearchQueryArgs = FindManySearchQueryArgsFromSearchQuery


    

class SearchQueryWhereInput(TypedDict, total=False):
    """SearchQuery arguments for searching"""
    id: Union[_str, 'types.StringFilter']
    filters: Union['fields.Json', 'types.JsonFilter']
    sqlQuery: Union[_str, 'types.StringFilter']
    resultCount: Union[_int, 'types.IntFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']

    # should be noted that AND and NOT should be Union['SearchQueryWhereInputRecursive1', List['SearchQueryWhereInputRecursive1']]
    # but this causes mypy to hang :/
    AND: List['SearchQueryWhereInputRecursive1']
    OR: List['SearchQueryWhereInputRecursive1']
    NOT: List['SearchQueryWhereInputRecursive1']


class SearchQueryWhereInputRecursive1(TypedDict, total=False):
    """SearchQuery arguments for searching"""
    id: Union[_str, 'types.StringFilter']
    filters: Union['fields.Json', 'types.JsonFilter']
    sqlQuery: Union[_str, 'types.StringFilter']
    resultCount: Union[_int, 'types.IntFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']

    # should be noted that AND and NOT should be Union['SearchQueryWhereInputRecursive2', List['SearchQueryWhereInputRecursive2']]
    # but this causes mypy to hang :/
    AND: List['SearchQueryWhereInputRecursive2']
    OR: List['SearchQueryWhereInputRecursive2']
    NOT: List['SearchQueryWhereInputRecursive2']


class SearchQueryWhereInputRecursive2(TypedDict, total=False):
    """SearchQuery arguments for searching"""
    id: Union[_str, 'types.StringFilter']
    filters: Union['fields.Json', 'types.JsonFilter']
    sqlQuery: Union[_str, 'types.StringFilter']
    resultCount: Union[_int, 'types.IntFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']

    # should be noted that AND and NOT should be Union['SearchQueryWhereInputRecursive3', List['SearchQueryWhereInputRecursive3']]
    # but this causes mypy to hang :/
    AND: List['SearchQueryWhereInputRecursive3']
    OR: List['SearchQueryWhereInputRecursive3']
    NOT: List['SearchQueryWhereInputRecursive3']


class SearchQueryWhereInputRecursive3(TypedDict, total=False):
    """SearchQuery arguments for searching"""
    id: Union[_str, 'types.StringFilter']
    filters: Union['fields.Json', 'types.JsonFilter']
    sqlQuery: Union[_str, 'types.StringFilter']
    resultCount: Union[_int, 'types.IntFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']

    # should be noted that AND and NOT should be Union['SearchQueryWhereInputRecursive4', List['SearchQueryWhereInputRecursive4']]
    # but this causes mypy to hang :/
    AND: List['SearchQueryWhereInputRecursive4']
    OR: List['SearchQueryWhereInputRecursive4']
    NOT: List['SearchQueryWhereInputRecursive4']


class SearchQueryWhereInputRecursive4(TypedDict, total=False):
    """SearchQuery arguments for searching"""
    id: Union[_str, 'types.StringFilter']
    filters: Union['fields.Json', 'types.JsonFilter']
    sqlQuery: Union[_str, 'types.StringFilter']
    resultCount: Union[_int, 'types.IntFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']



# aggregate SearchQuery types


    

class SearchQueryScalarWhereWithAggregatesInput(TypedDict, total=False):
    """SearchQuery arguments for searching"""
    id: Union[_str, 'types.StringWithAggregatesFilter']
    filters: Union['fields.Json', 'types.JsonWithAggregatesFilter']
    sqlQuery: Union[_str, 'types.StringWithAggregatesFilter']
    resultCount: Union[_int, 'types.IntWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']

    AND: List['SearchQueryScalarWhereWithAggregatesInputRecursive1']
    OR: List['SearchQueryScalarWhereWithAggregatesInputRecursive1']
    NOT: List['SearchQueryScalarWhereWithAggregatesInputRecursive1']


class SearchQueryScalarWhereWithAggregatesInputRecursive1(TypedDict, total=False):
    """SearchQuery arguments for searching"""
    id: Union[_str, 'types.StringWithAggregatesFilter']
    filters: Union['fields.Json', 'types.JsonWithAggregatesFilter']
    sqlQuery: Union[_str, 'types.StringWithAggregatesFilter']
    resultCount: Union[_int, 'types.IntWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']

    AND: List['SearchQueryScalarWhereWithAggregatesInputRecursive2']
    OR: List['SearchQueryScalarWhereWithAggregatesInputRecursive2']
    NOT: List['SearchQueryScalarWhereWithAggregatesInputRecursive2']


class SearchQueryScalarWhereWithAggregatesInputRecursive2(TypedDict, total=False):
    """SearchQuery arguments for searching"""
    id: Union[_str, 'types.StringWithAggregatesFilter']
    filters: Union['fields.Json', 'types.JsonWithAggregatesFilter']
    sqlQuery: Union[_str, 'types.StringWithAggregatesFilter']
    resultCount: Union[_int, 'types.IntWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']

    AND: List['SearchQueryScalarWhereWithAggregatesInputRecursive3']
    OR: List['SearchQueryScalarWhereWithAggregatesInputRecursive3']
    NOT: List['SearchQueryScalarWhereWithAggregatesInputRecursive3']


class SearchQueryScalarWhereWithAggregatesInputRecursive3(TypedDict, total=False):
    """SearchQuery arguments for searching"""
    id: Union[_str, 'types.StringWithAggregatesFilter']
    filters: Union['fields.Json', 'types.JsonWithAggregatesFilter']
    sqlQuery: Union[_str, 'types.StringWithAggregatesFilter']
    resultCount: Union[_int, 'types.IntWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']

    AND: List['SearchQueryScalarWhereWithAggregatesInputRecursive4']
    OR: List['SearchQueryScalarWhereWithAggregatesInputRecursive4']
    NOT: List['SearchQueryScalarWhereWithAggregatesInputRecursive4']


class SearchQueryScalarWhereWithAggregatesInputRecursive4(TypedDict, total=False):
    """SearchQuery arguments for searching"""
    id: Union[_str, 'types.StringWithAggregatesFilter']
    filters: Union['fields.Json', 'types.JsonWithAggregatesFilter']
    sqlQuery: Union[_str, 'types.StringWithAggregatesFilter']
    resultCount: Union[_int, 'types.IntWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']



class SearchQueryGroupByOutput(TypedDict, total=False):
    id: _str
    filters: 'fields.Json'
    sqlQuery: _str
    resultCount: _int
    createdAt: datetime.datetime
    _sum: 'SearchQuerySumAggregateOutput'
    _avg: 'SearchQueryAvgAggregateOutput'
    _min: 'SearchQueryMinAggregateOutput'
    _max: 'SearchQueryMaxAggregateOutput'
    _count: 'SearchQueryCountAggregateOutput'


class SearchQueryAvgAggregateOutput(TypedDict, total=False):
    """SearchQuery output for aggregating averages"""
    resultCount: float


class SearchQuerySumAggregateOutput(TypedDict, total=False):
    """SearchQuery output for aggregating sums"""
    resultCount: _int


class SearchQueryScalarAggregateOutput(TypedDict, total=False):
    """SearchQuery output including scalar fields"""
    id: _str
    filters: 'fields.Json'
    sqlQuery: _str
    resultCount: _int
    createdAt: datetime.datetime


SearchQueryMinAggregateOutput = SearchQueryScalarAggregateOutput
SearchQueryMaxAggregateOutput = SearchQueryScalarAggregateOutput


class SearchQueryMaxAggregateInput(TypedDict, total=False):
    """SearchQuery input for aggregating by max"""
    id: bool
    filters: bool
    sqlQuery: bool
    resultCount: bool
    createdAt: bool


class SearchQueryMinAggregateInput(TypedDict, total=False):
    """SearchQuery input for aggregating by min"""
    id: bool
    filters: bool
    sqlQuery: bool
    resultCount: bool
    createdAt: bool


class SearchQueryNumberAggregateInput(TypedDict, total=False):
    """SearchQuery input for aggregating numbers"""
    resultCount: bool


SearchQueryAvgAggregateInput = SearchQueryNumberAggregateInput
SearchQuerySumAggregateInput = SearchQueryNumberAggregateInput


SearchQueryCountAggregateInput = TypedDict(
    'SearchQueryCountAggregateInput',
    {
        'id': bool,
        'filters': bool,
        'sqlQuery': bool,
        'resultCount': bool,
        'createdAt': bool,
        '_all': bool,
    },
    total=False,
)

SearchQueryCountAggregateOutput = TypedDict(
    'SearchQueryCountAggregateOutput',
    {
        'id': int,
        'filters': int,
        'sqlQuery': int,
        'resultCount': int,
        'createdAt': int,
        '_all': int,
    },
    total=False,
)


SearchQueryKeys = Literal[
    'id',
    'filters',
    'sqlQuery',
    'resultCount',
    'createdAt',
]
SearchQueryScalarFieldKeys = Literal[
    'id',
    'filters',
    'sqlQuery',
    'resultCount',
    'createdAt',
]
SearchQueryScalarFieldKeysT = TypeVar('SearchQueryScalarFieldKeysT', bound=SearchQueryScalarFieldKeys)

SearchQueryRelationalFieldKeys = _NoneType



# we have to import ourselves as types can be namespaced to types
from . import types, enums, models, fields